@php
    $record = $delivery ?? null;
    $labour = $labour ?? $record?->labour;
    $patient = $record?->patient ?? $labour?->patient;
    $fieldClass = 'mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm placeholder:text-med-muted/70';
    $labelClass = 'mb-1 block text-sm font-medium text-med-ink';
    $value = fn ($name, $default = '') => old($name, data_get($record, $name, $default));
    $dateValue = fn ($name, $default = null) => old($name, data_get($record, $name)?->format('Y-m-d\TH:i') ?? $default);
@endphp
@if ($errors->any())<div class="rounded-md border border-med-danger/25 bg-red-50 px-4 py-3 text-sm text-med-danger"><p class="font-semibold">Please fix the highlighted errors.</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 xl:grid-cols-12"><div class="space-y-6 xl:col-span-8">
<x-ui.card title="Delivery Details"><div class="grid gap-4 md:grid-cols-2"><label><span class="{{ $labelClass }}">Delivery Date & Time</span><input type="datetime-local" name="delivery_date_time" value="{{ $dateValue('delivery_date_time', now()->format('Y-m-d\TH:i')) }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Delivery Type</span><select name="delivery_type" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['vaginal'=>'Vaginal','assisted_vaginal'=>'Assisted Vaginal','caesarean'=>'Caesarean Section'] as $key=>$label)<option value="{{ $key }}" @selected($value('delivery_type','vaginal')===$key)>{{ $label }}</option>@endforeach</select></label><label class="md:col-span-2"><span class="{{ $labelClass }}">Reason for Delivery Type</span><textarea name="reason_for_delivery_type" rows="3" class="{{ $fieldClass }}">{{ $value('reason_for_delivery_type') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Assisted And Caesarean Details"><div class="grid gap-4 md:grid-cols-2"><label><span class="{{ $labelClass }}">Assisted With</span><select name="assisted_with" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['vacuum'=>'Vacuum','forceps'=>'Forceps'] as $key=>$label)<option value="{{ $key }}" @selected($value('assisted_with')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Caesarean Type</span><select name="caesarean_type" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['elective'=>'Elective','emergency'=>'Emergency'] as $key=>$label)<option value="{{ $key }}" @selected($value('caesarean_type')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Indication for Assistance</span><textarea name="indication_for_assistance" rows="3" class="{{ $fieldClass }}">{{ $value('indication_for_assistance') }}</textarea></label><label><span class="{{ $labelClass }}">Indication for Caesarean</span><textarea name="indication_for_caesarean" rows="3" class="{{ $fieldClass }}">{{ $value('indication_for_caesarean') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Perineum And Placenta"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Perineal Trauma</span><select name="perineal_trauma" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['intact'=>'Intact','1st degree'=>'1st Degree','2nd degree'=>'2nd Degree','3rd degree'=>'3rd Degree','4th degree'=>'4th Degree'] as $key=>$label)<option value="{{ $key }}" @selected($value('perineal_trauma')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Placenta Delivery Method</span><select name="placenta_delivery_method" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['spontaneous'=>'Spontaneous','manual removal'=>'Manual Removal'] as $key=>$label)<option value="{{ $key }}" @selected($value('placenta_delivery_method')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Placenta Delivered At</span><input type="datetime-local" name="placenta_delivered_at" value="{{ $dateValue('placenta_delivered_at') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Episiotomy</span><textarea name="episiotomy" rows="3" class="{{ $fieldClass }}">{{ $value('episiotomy') }}</textarea></label><label><span class="{{ $labelClass }}">Perineal Repair</span><textarea name="perineal_repair" rows="3" class="{{ $fieldClass }}">{{ $value('perineal_repair') }}</textarea></label><label><span class="{{ $labelClass }}">Placental Examination</span><textarea name="placental_examination" rows="3" class="{{ $fieldClass }}">{{ $value('placental_examination') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Maternal Condition And Outcome"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Estimated Blood Loss</span><input type="text" name="estimated_blood_loss" value="{{ $value('estimated_blood_loss') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Blood Pressure</span><input type="text" name="blood_pressure" value="{{ $value('blood_pressure') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Pulse Rate</span><input type="text" name="pulse_rate" value="{{ $value('pulse_rate') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Uterine Tone</span><input type="text" name="uterine_tone" value="{{ $value('uterine_tone') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Per Vaginal Bleeding</span><input type="text" name="per_vaginal_bleeding" value="{{ $value('per_vaginal_bleeding') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">General Condition</span><input type="text" name="general_condition" value="{{ $value('general_condition') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Number of Babies</span><input type="number" min="1" max="10" name="number_of_babies" value="{{ $value('number_of_babies', 1) }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Delivery Status</span><select name="delivery_status" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['successful'=>'Successful','complicated'=>'Complicated','maternal_death'=>'Maternal Death','fetal_death'=>'Fetal Death'] as $key=>$label)<option value="{{ $key }}" @selected($value('delivery_status','successful')===$key)>{{ $label }}</option>@endforeach</select></label><label class="md:col-span-3"><span class="{{ $labelClass }}">Blood Loss Assessment</span><textarea name="blood_loss_assessment" rows="3" class="{{ $fieldClass }}">{{ $value('blood_loss_assessment') }}</textarea></label><label class="md:col-span-3"><span class="{{ $labelClass }}">Complications</span><textarea name="complications" rows="3" class="{{ $fieldClass }}">{{ $value('complications') }}</textarea></label><label class="md:col-span-3"><span class="{{ $labelClass }}">Management of Complications</span><textarea name="management_of_complications" rows="3" class="{{ $fieldClass }}">{{ $value('management_of_complications') }}</textarea></label><label class="md:col-span-3"><span class="{{ $labelClass }}">Delivery Summary</span><textarea name="delivery_summary" rows="4" class="{{ $fieldClass }}">{{ $value('delivery_summary') }}</textarea></label></div></x-ui.card>
</div><aside class="space-y-6 xl:col-span-4"><x-ui.card title="Patient Context"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Patient</dt><dd class="font-semibold text-med-ink">{{ $patient?->name() ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Hospital Number</dt><dd class="font-semibold text-med-ink">{{ $patient?->hospital_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Labour</dt><dd class="font-semibold text-med-ink">{{ $labour?->labour_onset_time?->format('M d, Y h:i A') ?? 'Direct visit record' }}</dd></div></dl></x-ui.card><x-ui.card title="Save Delivery"><div class="flex flex-col gap-2"><x-ui.button type="submit">{{ $submitLabel ?? 'Save Delivery' }}</x-ui.button><a href="{{ $cancelRoute ?? route('midwife.delivery.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Cancel</a></div></x-ui.card></aside></div>
