@extends('layouts.modern')
@section('title', 'Delivery Record')
@section('content')
@php
    $patient=$delivery->patient;
    $statusVariant=$delivery->delivery_status==='successful'?'success':($delivery->delivery_status==='complicated'?'warning':'danger');
    $sections=[
        'Delivery Details'=>['Delivery Date & Time'=>optional($delivery->delivery_date_time)->format('M d, Y h:i A') ?? 'N/A','Delivery Type'=>str($delivery->delivery_type)->headline(),'Number of Babies'=>$delivery->number_of_babies ?? 'N/A','Reason for Delivery Type'=>$delivery->reason_for_delivery_type ?? 'N/A'],
        'Assisted And Caesarean Details'=>['Assisted With'=>str($delivery->assisted_with ?? 'N/A')->headline(),'Indication for Assistance'=>$delivery->indication_for_assistance ?? 'N/A','Caesarean Type'=>str($delivery->caesarean_type ?? 'N/A')->headline(),'Indication for Caesarean'=>$delivery->indication_for_caesarean ?? 'N/A'],
        'Perineum And Placenta'=>['Perineal Trauma'=>$delivery->perineal_trauma ?? 'N/A','Episiotomy'=>$delivery->episiotomy ?? 'N/A','Perineal Repair'=>$delivery->perineal_repair ?? 'N/A','Placenta Delivery Method'=>str($delivery->placenta_delivery_method ?? 'N/A')->headline(),'Placenta Delivered At'=>optional($delivery->placenta_delivered_at)->format('M d, Y h:i A') ?? 'N/A','Placental Examination'=>$delivery->placental_examination ?? 'N/A'],
        'Maternal Condition'=>['Estimated Blood Loss'=>$delivery->estimated_blood_loss ?? 'N/A','Blood Pressure'=>$delivery->blood_pressure ?? 'N/A','Pulse Rate'=>$delivery->pulse_rate ?? 'N/A','General Condition'=>$delivery->general_condition ?? 'N/A','Uterine Tone'=>$delivery->uterine_tone ?? 'N/A','Per Vaginal Bleeding'=>$delivery->per_vaginal_bleeding ?? 'N/A','Blood Loss Assessment'=>$delivery->blood_loss_assessment ?? 'N/A'],
        'Complications And Summary'=>['Complications'=>$delivery->complications ?? 'N/A','Management of Complications'=>$delivery->management_of_complications ?? 'N/A','Delivery Summary'=>$delivery->delivery_summary ?? 'N/A'],
    ];
@endphp
<x-ui.page title="Delivery Record" subtitle="{{ $patient->name() }} | {{ optional($delivery->delivery_date_time)->format('M d, Y h:i A') }}"><x-slot name="actions"><a href="{{ route('midwife.delivery.edit', $delivery) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Edit</a><a href="{{ $delivery->labour_id ? route('midwife.labour.show', $delivery->labour_id) : route('midwife.delivery-management', $patient) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">{{ $delivery->labour_id ? 'Back' : 'Delivery Management' }}</a></x-slot>
<div class="grid gap-6 xl:grid-cols-12"><div class="space-y-6 xl:col-span-8">@foreach($sections as $title=>$items)<x-ui.card title="{{ $title }}"><dl class="grid gap-4 md:grid-cols-2">@foreach($items as $label=>$value)<div><dt class="text-sm font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-sm font-semibold text-med-ink">{{ $value }}</dd></div>@endforeach</dl></x-ui.card>@endforeach</div><aside class="space-y-6 xl:col-span-4"><x-ui.card title="Patient Information"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Hospital Number</dt><dd class="font-semibold text-med-ink">{{ $patient->hospital_number }}</dd></div><div><dt class="text-med-muted">Patient Name</dt><dd class="font-semibold text-med-ink">{{ $patient->name() }}</dd></div><div><dt class="text-med-muted">Age</dt><dd class="font-semibold text-med-ink">{{ $patient->age() }} years</dd></div><div><dt class="text-med-muted">Delivery Status</dt><dd><x-ui.badge :variant="$statusVariant">{{ str($delivery->delivery_status)->headline() }}</x-ui.badge></dd></div></dl></x-ui.card><x-ui.card title="Record Metadata"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Delivered By</dt><dd class="font-semibold text-med-ink">{{ $delivery->deliveredBy->name ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Assisted By</dt><dd class="font-semibold text-med-ink">{{ $delivery->assistedBy->name ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Created At</dt><dd class="font-semibold text-med-ink">{{ $delivery->created_at->format('M d, Y h:i A') }}</dd></div><div><dt class="text-med-muted">Record ID</dt><dd class="font-semibold text-med-ink">#{{ $delivery->id }}</dd></div></dl></x-ui.card></aside></div>
</x-ui.page>
@endsection
