<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Statistics Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 7px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { border-bottom: 2px solid #198754; padding-bottom: 10px; margin-bottom: 12px; }
        .header td { border: 0; padding: 0; }
        .logo { width: 72px; height: 72px; object-fit: contain; }
        .hospital-name { font-size: 17px; font-weight: bold; color: #198754; }
        .report-meta { font-size: 10px; color: #555; text-align: right; }
        .muted { color: #666; }
        .summary td { width: 25%; }
        .count { text-align: right; font-weight: bold; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 86px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Statistics Report</h1>
                <div class="muted">{{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</div>
            </td>
            <td class="report-meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Total Activities</strong><br>{{ number_format(collect($statistics)->sum('value')) }}</td>
            <td><strong>From</strong><br>{{ $startDate->format('Y-m-d') }}</td>
            <td><strong>To</strong><br>{{ $endDate->format('Y-m-d') }}</td>
            <td><strong>Gender</strong><br>{{ request('gender', 'All') ?: 'All' }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Statistic</th>
                <th class="count">Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($statistics as $stat)
                <tr>
                    <td>{{ $stat['label'] }}</td>
                    <td class="count">{{ number_format($stat['value']) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
