<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Pharmacy Financial Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #222; }
        h1 { font-size: 19px; margin: 0 0 4px; }
        h2 { font-size: 13px; margin: 14px 0 6px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 5px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { border-bottom: 2px solid #198754; margin-bottom: 10px; }
        .header td { border: 0; padding: 0 0 8px; }
        .logo { width: 70px; height: 70px; object-fit: contain; }
        .hospital-name { font-size: 17px; font-weight: bold; color: #198754; }
        .meta { text-align: right; color: #555; }
        .summary td { width: 16.66%; }
        .text-end { text-align: right; }
        .muted { color: #666; }
        .positive { color: #0f7a39; }
        .negative { color: #b42318; }
        .bar-track { width: 100%; height: 12px; background: #eef1f4; }
        .bar { height: 12px; }
        .chart-table td { border: 0; padding: 4px; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 84px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Pharmacy Financial Report</h1>
                <div class="muted">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</div>
            </td>
            <td class="meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Transactions</strong><br>{{ number_format($summary['transactions']) }}</td>
            <td><strong>Bills</strong><br>{{ number_format($summary['bills'], 2) }}</td>
            <td><strong>Payments</strong><br>{{ number_format($summary['payments'], 2) }}</td>
            <td><strong>Stock Cost</strong><br>{{ number_format($summary['cost'], 2) }}</td>
            <td><strong>Gross Profit</strong><br><span class="{{ $summary['profit'] >= 0 ? 'positive' : 'negative' }}">{{ number_format($summary['profit'], 2) }}</span></td>
            <td><strong>Items</strong><br>{{ number_format($summary['items']) }}</td>
        </tr>
    </table>

    <h2>Report Chart</h2>
    @php $maxTotal = max(collect($chartTotals)->max('value') ?: 1, 1); @endphp
    <table class="chart-table">
        @foreach($chartTotals as $bar)
            @php $width = max(3, abs($bar['value']) / $maxTotal * 100); @endphp
            <tr>
                <td style="width: 120px;">{{ $bar['label'] }}</td>
                <td>
                    <div class="bar-track"><div class="bar" style="width: {{ $width }}%; background: {{ $bar['color'] }};"></div></div>
                </td>
                <td class="text-end" style="width: 110px;">{{ number_format($bar['value'], 2) }}</td>
            </tr>
        @endforeach
    </table>

    <h2>Top Medicines By Profit</h2>
    <table>
        <thead>
            <tr>
                <th>Medicine</th>
                <th class="text-end">Qty</th>
                <th class="text-end">Revenue</th>
                <th class="text-end">Cost</th>
                <th class="text-end">Profit</th>
            </tr>
        </thead>
        <tbody>
            @forelse($topMedicines as $medicine)
                <tr>
                    <td>{{ $medicine['name'] }}</td>
                    <td class="text-end">{{ number_format($medicine['quantity']) }}</td>
                    <td class="text-end">{{ number_format($medicine['revenue'], 2) }}</td>
                    <td class="text-end">{{ number_format($medicine['cost'], 2) }}</td>
                    <td class="text-end {{ $medicine['profit'] >= 0 ? 'positive' : 'negative' }}">{{ number_format($medicine['profit'], 2) }}</td>
                </tr>
            @empty
                <tr><td colspan="5">No medicine profit data found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Transaction Details</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Bill</th>
                <th>Receipt</th>
                <th>Medicines</th>
                <th>Collected By</th>
                <th class="text-end">Revenue</th>
                <th class="text-end">Cost</th>
                <th class="text-end">Profit</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactionRows as $row)
                @php $transaction = $row['transaction']; @endphp
                <tr>
                    <td>{{ $transaction->created_at?->format('Y-m-d H:i') }}</td>
                    <td>{{ $transaction->bill?->bill_number ?? 'N/A' }}</td>
                    <td>{{ $transaction->payment?->payment_id ?? 'N/A' }}</td>
                    <td>
                        @foreach($transaction->stockTransactionItems as $item)
                            {{ $item->medicineBatch?->medicine?->name ?? 'N/A' }} x {{ $item->quantity }}@if(! $loop->last); @endif
                        @endforeach
                    </td>
                    <td>{{ $transaction->createdBy?->name ?? 'System' }}</td>
                    <td class="text-end">{{ number_format($row['revenue'], 2) }}</td>
                    <td class="text-end">{{ number_format($row['cost'], 2) }}</td>
                    <td class="text-end {{ $row['profit'] >= 0 ? 'positive' : 'negative' }}">{{ number_format($row['profit'], 2) }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No pharmacy finance record found for this period.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
