@extends('layouts.modern')

@section('title', 'Pharmacy Financial Report')

@section('content')
    <x-ui.page title="Pharmacy Financial Report" subtitle="Bills, payments, stock cost, and transaction totals for dispensed medicines.">
        <x-slot:actions><a href="{{ route('pharmacy.finance.report.download', ['from' => $from, 'to' => $to]) }}" class="mf-focus inline-flex items-center justify-center gap-2 rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-med-primaryDark"><i class="bi bi-download"></i>Download Report</a><a href="{{ route('pharmacy.finance.payments') }}" class="mf-focus inline-flex items-center justify-center gap-2 rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink shadow-sm transition hover:bg-med-canvas"><i class="bi bi-credit-card-2-front"></i>Payments</a></x-slot:actions>
        <form method="GET" action="{{ route('pharmacy.finance.report') }}"><x-ui.card title="Report Filters"><div class="grid gap-4 md:grid-cols-3 md:items-end"><x-ui.input label="From" type="date" name="from" value="{{ $from }}" /><x-ui.input label="To" type="date" name="to" value="{{ $to }}" /><x-ui.button type="submit"><i class="bi bi-search"></i>Filter</x-ui.button></div></x-ui.card></form>
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-6"><x-ui.card><p class="text-sm font-medium text-med-muted">Transactions</p><p class="mt-2 text-2xl font-bold text-med-ink">{{ number_format($summary['transactions']) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Bills</p><p class="mt-2 text-2xl font-bold text-med-ink">&#8358;{{ number_format($summary['bills'], 2) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Payments</p><p class="mt-2 text-2xl font-bold text-med-ink">&#8358;{{ number_format($summary['payments'], 2) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Stock Cost</p><p class="mt-2 text-2xl font-bold text-med-ink">&#8358;{{ number_format($summary['cost'], 2) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Gross Profit</p><p class="mt-2 text-2xl font-bold {{ $summary['profit'] >= 0 ? 'text-med-primary' : 'text-med-danger' }}">&#8358;{{ number_format($summary['profit'], 2) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Items Dispensed</p><p class="mt-2 text-2xl font-bold text-med-ink">{{ number_format($summary['items']) }}</p></x-ui.card></div>
        <div class="grid gap-6 xl:grid-cols-12"><x-ui.card class="xl:col-span-5" title="Revenue, Cost, and Profit">@php $maxTotal = max(collect($chartTotals)->max('value') ?: 1, 1); @endphp <div class="space-y-4">@foreach($chartTotals as $bar) @php $width = max(3, abs($bar['value']) / $maxTotal * 100); @endphp <div><div class="mb-1 flex justify-between text-sm"><span class="text-med-muted">{{ $bar['label'] }}</span><strong class="text-med-ink">&#8358;{{ number_format($bar['value'], 2) }}</strong></div><div class="h-3 overflow-hidden rounded-full bg-med-canvas"><div class="h-full rounded-full bg-med-primary" style="width: {{ $width }}%"></div></div></div> @endforeach</div></x-ui.card><x-ui.card class="xl:col-span-7" title="Daily Gross Profit">@php $maxDaily = max($dailyProfit->max('value') ?: 1, 1); @endphp <div class="space-y-3">@forelse($dailyProfit as $day) @php $width = max(3, abs($day['value']) / $maxDaily * 100); @endphp <div class="grid grid-cols-[80px_1fr_130px] items-center gap-3 text-sm"><span class="text-med-muted">{{ $day['label'] }}</span><div class="h-3 overflow-hidden rounded-full bg-med-canvas"><div class="h-full rounded-full bg-med-info" style="width: {{ $width }}%"></div></div><span class="text-right font-semibold text-med-ink">&#8358;{{ number_format($day['value'], 2) }}</span></div> @empty <x-ui.empty-state title="No Profit Chart Data" message="No profit chart data exists for this period." /> @endforelse</div></x-ui.card></div>
        <x-ui.card title="Finance Records"><x-ui.table class="shadow-none"><thead class="bg-med-canvas text-left text-xs font-semibold uppercase text-med-muted"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Bill</th><th class="px-4 py-3">Receipt</th><th class="px-4 py-3">Medicines</th><th class="px-4 py-3">Collected By</th><th class="px-4 py-3 text-right">Cost</th><th class="px-4 py-3 text-right">Profit</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-med-line bg-white">@forelse($transactionRows as $row) @php $transaction = $row['transaction']; @endphp <tr><td class="px-4 py-4 text-med-muted">{{ $transaction->created_at?->format('M d, Y h:i A') }}</td><td class="px-4 py-4 font-semibold text-med-ink">{{ $transaction->bill?->bill_number ?? 'N/A' }}</td><td class="px-4 py-4 text-med-muted">{{ $transaction->payment?->payment_id ?? 'N/A' }}</td><td class="px-4 py-4 text-med-muted">@foreach($transaction->stockTransactionItems as $item)<div>{{ $item->medicineBatch?->medicine?->name ?? 'N/A' }} <span>x {{ $item->quantity }}</span></div>@endforeach</td><td class="px-4 py-4 text-med-muted">{{ $transaction->createdBy?->name ?? 'System' }}</td><td class="px-4 py-4 text-right text-med-muted">&#8358;{{ number_format($row['cost'], 2) }}</td><td class="px-4 py-4 text-right font-semibold {{ $row['profit'] >= 0 ? 'text-med-primary' : 'text-med-danger' }}">&#8358;{{ number_format($row['profit'], 2) }}</td><td class="px-4 py-4 text-right font-semibold text-med-ink">&#8358;{{ number_format($row['revenue'], 2) }}</td></tr> @empty <tr><td colspan="8" class="px-4 py-8"><x-ui.empty-state title="No Finance Record" message="No pharmacy finance record was found for this period." /></td></tr> @endforelse</tbody></x-ui.table></x-ui.card>
    </x-ui.page>
@endsection
