@extends('layouts.modern')

@section('title', 'Maternal Journey Tracker')

@section('content')
@php
    $stages = [
        ['title' => 'Antenatal Care Registration', 'completed' => !is_null($antenatalCare), 'view_route' => $antenatalCare ? route('midwife.antenatal.show', $antenatalCare) : null, 'create_route' => route('midwife.antenatal.create', $patient), 'date' => $antenatalCare?->created_at],
        ['title' => 'Labour Registration', 'completed' => !is_null($labour), 'view_route' => $labour ? route('midwife.labour.show', $labour) : null, 'create_route' => $antenatalCare ? route('midwife.labour.create', $patient) : null, 'date' => $labour?->created_at],
        ['title' => 'Delivery Record', 'completed' => !is_null($delivery), 'view_route' => $delivery ? route('midwife.delivery.show', $delivery) : null, 'create_route' => $labour ? route('midwife.delivery.create', $labour) : null, 'date' => $delivery?->created_at],
        ['title' => 'Newborn Registration', 'completed' => $newborns->count() > 0, 'view_route' => $newborns->count() ? route('midwife.newborn.show', $newborns->first()) : null, 'create_route' => $delivery ? route('midwife.newborn.create', $delivery) : null, 'date' => $newborns->count() ? $newborns->first()->created_at : null],
        ['title' => 'Newborn Examination', 'completed' => $newbornExaminations->count() > 0, 'view_route' => $newbornExaminations->count() ? route('midwife.newborn-examination.show', $newbornExaminations->first()) : null, 'create_route' => $newborns->count() ? route('midwife.newborn-examination.create', $newborns->first()) : null, 'date' => $newbornExaminations->count() ? $newbornExaminations->first()->created_at : null],
        ['title' => 'Postnatal Examination', 'completed' => $postnatalExaminations->count() > 0, 'view_route' => $postnatalExaminations->count() ? route('midwife.postnatal-examination.show', $postnatalExaminations->first()) : null, 'create_route' => $delivery ? route('midwife.postnatal-examination.create', $delivery) : null, 'date' => $postnatalExaminations->count() ? $postnatalExaminations->first()->created_at : null],
        ['title' => 'Child Follow-up', 'completed' => $childFollowUps->count() > 0, 'view_route' => $childFollowUps->count() ? route('midwife.child-follow-up.show', $childFollowUps->first()) : null, 'create_route' => $newborns->count() ? route('midwife.child-follow-up.create', $newborns->first()) : null, 'date' => $childFollowUps->count() ? $childFollowUps->first()->created_at : null],
    ];
    $completedStages = collect($stages)->where('completed', true)->count();
    $totalStages = count($stages);
    $progressPercentage = round(($completedStages / $totalStages) * 100);
@endphp
<x-ui.page title="Maternal Journey Tracker" subtitle="{{ $patient->name() }} - Hospital No: {{ $patient->hospital_number }}">
    <x-slot name="actions"><x-ui.badge>{{ $progressPercentage }}% Completed</x-ui.badge></x-slot>
    <div class="space-y-6"><x-ui.card title="Maternal Journey Progress"><div class="mb-2 flex items-center justify-between text-sm font-semibold text-med-ink"><span>Journey Progress</span><span>{{ $completedStages }} / {{ $totalStages }} stages completed</span></div><div class="h-3 overflow-hidden rounded-full bg-med-canvas"><div class="h-full rounded-full bg-med-success transition-all" style="width: {{ $progressPercentage }}%"></div></div></x-ui.card>
    <x-ui.card title="Maternal Care Journey Timeline"><div class="space-y-4">@foreach($stages as $index => $stage)@php($previousCompleted = $index === 0 ? true : $stages[$index - 1]['completed'])@php($isCurrentStage = !$stage['completed'] && $previousCompleted)<article class="grid gap-4 rounded-md border border-med-line p-4 md:grid-cols-[48px_1fr_auto] md:items-center"><div class="flex h-12 w-12 items-center justify-center rounded-full {{ $stage['completed'] ? 'bg-med-success text-white' : ($isCurrentStage ? 'bg-med-warning/20 text-med-warning' : 'bg-med-canvas text-med-muted') }}"><span class="text-sm font-bold">{{ $index + 1 }}</span></div><div><h3 class="text-base font-semibold text-med-ink">{{ $stage['title'] }}</h3><div class="mt-2 flex flex-wrap items-center gap-2">@if($stage['completed'])<x-ui.badge variant="success">Completed</x-ui.badge>@elseif($isCurrentStage)<x-ui.badge variant="warning">Current Stage</x-ui.badge>@else<x-ui.badge>Pending</x-ui.badge>@endif @if($stage['date'])<span class="text-sm text-med-muted">Recorded: {{ $stage['date']->format('M d, Y h:i A') }}</span>@endif</div></div><div class="flex justify-start md:justify-end">@if($stage['completed'])<a href="{{ $stage['view_route'] }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">View Record</a>@elseif($isCurrentStage && $stage['create_route'])<a href="{{ $stage['create_route'] }}" class="inline-flex items-center justify-center rounded-md border border-med-warning bg-med-warning px-3 py-2 text-sm font-semibold text-white transition hover:brightness-95">Start Stage</a>@else<button class="inline-flex cursor-not-allowed items-center justify-center rounded-md border border-med-line bg-med-canvas px-3 py-2 text-sm font-semibold text-med-muted" disabled>Waiting Previous Stage</button>@endif</div></article>@endforeach</div><div class="mt-6"><a href="{{ route('midwife.antenatal.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back to Patients List</a></div></x-ui.card></div>
</x-ui.page>
@endsection
