@php
    $record = $newbornExamination ?? null;
    $newborn = $newborn ?? $record?->newborn;
    $patient = $newborn?->patient;
    $fieldClass = 'mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm placeholder:text-med-muted/70';
    $labelClass = 'mb-1 block text-sm font-medium text-med-ink';
    $value = fn ($name, $default = '') => old($name, data_get($record, $name, $default));
    $dateValue = fn ($name, $default = null) => old($name, data_get($record, $name)?->format('Y-m-d\TH:i') ?? $default);
@endphp
@if ($errors->any())<div class="rounded-md border border-med-danger/25 bg-red-50 px-4 py-3 text-sm text-med-danger"><p class="font-semibold">Please fix the highlighted errors.</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 xl:grid-cols-12"><div class="space-y-6 xl:col-span-8">
<x-ui.card title="Examination Details"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Examination Date & Time</span><input type="datetime-local" name="examination_date_time" value="{{ $dateValue('examination_date_time', now()->format('Y-m-d\TH:i')) }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Hours After Birth</span><input type="number" min="0" name="hours_after_birth" value="{{ $value('hours_after_birth') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Examination Status</span><select name="exam_status" class="{{ $fieldClass }}">@foreach(['normal'=>'Normal','abnormal'=>'Abnormal','needs_follow_up'=>'Needs Follow-up','referral_needed'=>'Referral Needed'] as $key=>$label)<option value="{{ $key }}" @selected($value('exam_status','normal')===$key)>{{ $label }}</option>@endforeach</select></label></div></x-ui.card>
<x-ui.card title="Vitals And Anthropometry"><div class="grid gap-4 md:grid-cols-4">@foreach(['temperature'=>'Temperature','heart_rate'=>'Heart Rate','respiratory_rate'=>'Respiratory Rate','weight'=>'Weight','length'=>'Length','head_circumference'=>'Head Circumference','chest_circumference'=>'Chest Circumference'] as $name=>$label)<label><span class="{{ $labelClass }}">{{ $label }}</span><input type="number" step="0.1" name="{{ $name }}" value="{{ $value($name) }}" class="{{ $fieldClass }}"></label>@endforeach</div></x-ui.card>
<x-ui.card title="Body Systems"><div class="grid gap-4 md:grid-cols-2">@foreach(['general_appearance'=>'General Appearance','skin_examination'=>'Skin Examination','head_and_neck'=>'Head And Neck','eyes_examination'=>'Eyes Examination','ear_examination'=>'Ear Examination','mouth_and_throat'=>'Mouth And Throat','heart_sounds'=>'Heart Sounds','pulses'=>'Pulses','capillary_refill'=>'Capillary Refill','chest_expansion'=>'Chest Expansion','breath_sounds'=>'Breath Sounds','nasal_breathing'=>'Nasal Breathing','abdomen_shape'=>'Abdomen Shape','umbilical_cord_check'=>'Umbilical Cord Check','hepatomegaly_splenomegaly'=>'Hepatomegaly / Splenomegaly','bowel_sounds'=>'Bowel Sounds','genitalia_examination'=>'Genitalia Examination','urinary_output'=>'Urinary Output','stool_output'=>'Stool Output','reflex_assessment'=>'Reflex Assessment','muscle_tone'=>'Muscle Tone','developmental_screening'=>'Developmental Screening','extremities_examination'=>'Extremities Examination','hip_examination'=>'Hip Examination','spine_examination'=>'Spine Examination'] as $name=>$label)<label><span class="{{ $labelClass }}">{{ $label }}</span><textarea name="{{ $name }}" rows="2" class="{{ $fieldClass }}">{{ $value($name) }}</textarea></label>@endforeach</div></x-ui.card>
<x-ui.card title="Special Findings"><div class="grid gap-4 md:grid-cols-2"><label><span class="{{ $labelClass }}">Abnormal Findings</span><textarea name="abnormal_findings" rows="3" class="{{ $fieldClass }}">{{ $value('abnormal_findings') }}</textarea></label><label><span class="{{ $labelClass }}">Congenital Anomalies</span><textarea name="congenital_anomalies" rows="3" class="{{ $fieldClass }}">{{ $value('congenital_anomalies') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Jaundice And Feeding"><div class="grid gap-4 md:grid-cols-3"><label class="flex items-center gap-2 text-sm font-medium text-med-ink md:col-span-3"><input type="checkbox" name="jaundice_present" value="1" class="rounded border-med-line text-med-primary focus:ring-med-primary" @checked((bool) $value('jaundice_present'))> Jaundice Present</label><label><span class="{{ $labelClass }}">Jaundice Level</span><textarea name="jaundice_level" rows="2" class="{{ $fieldClass }}">{{ $value('jaundice_level') }}</textarea></label><label><span class="{{ $labelClass }}">Jaundice Management</span><textarea name="jaundice_management" rows="2" class="{{ $fieldClass }}">{{ $value('jaundice_management') }}</textarea></label><label><span class="{{ $labelClass }}">Feeding Type</span><select name="feeding_type" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['breast'=>'Breast Feeding','bottle'=>'Bottle Feeding','mixed'=>'Mixed Feeding'] as $key=>$label)<option value="{{ $key }}" @selected($value('feeding_type')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Feeding Tolerance</span><textarea name="feeding_tolerance" rows="2" class="{{ $fieldClass }}">{{ $value('feeding_tolerance') }}</textarea></label><label><span class="{{ $labelClass }}">Feeding Challenges</span><textarea name="feeding_challenges" rows="2" class="{{ $fieldClass }}">{{ $value('feeding_challenges') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Clinical Summary"><div class="grid gap-4 md:grid-cols-2"><label class="md:col-span-2"><span class="{{ $labelClass }}">Clinical Summary</span><textarea name="clinical_summary" rows="4" class="{{ $fieldClass }}">{{ $value('clinical_summary') }}</textarea></label><label><span class="{{ $labelClass }}">Follow-up Plans</span><textarea name="follow_up_plans" rows="3" class="{{ $fieldClass }}">{{ $value('follow_up_plans') }}</textarea></label><label><span class="{{ $labelClass }}">Next Follow-up Date</span><input type="datetime-local" name="next_follow_up_date" value="{{ $dateValue('next_follow_up_date') }}" class="{{ $fieldClass }}"></label></div></x-ui.card>
</div><aside class="space-y-6 xl:col-span-4"><x-ui.card title="Newborn Context"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Registration #</dt><dd class="font-semibold text-med-ink">{{ $newborn?->newborn_registration_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Mother</dt><dd class="font-semibold text-med-ink">{{ $patient?->name() ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Birth Date</dt><dd class="font-semibold text-med-ink">{{ $newborn?->birth_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Birth Weight</dt><dd class="font-semibold text-med-ink">{{ $newborn?->birth_weight ?? 'N/A' }}</dd></div></dl></x-ui.card><x-ui.card title="Save Examination"><div class="flex flex-col gap-2"><x-ui.button type="submit">{{ $submitLabel ?? 'Save Examination' }}</x-ui.button><a href="{{ $cancelRoute ?? route('midwife.newborn-examination.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Cancel</a></div></x-ui.card></aside></div>
