@extends('layouts.modern')

@section('title', 'Newborn Examination Records')

@section('content')
@php($examinations = $newborn->examinations->sortByDesc('examination_date_time'))
<x-ui.page title="Newborn Examination History" subtitle="Newborn {{ $newborn->newborn_registration_number ?? 'N/A' }} - Mother: {{ $newborn->patient->name() }}">
    <x-slot name="actions"><a href="{{ route('midwife.newborn-examination.create', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">New Examination</a><a href="{{ route('midwife.newborn.show', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6">
        <x-ui.card title="Newborn Summary"><dl class="grid gap-4 text-sm md:grid-cols-5"><div><dt class="text-med-muted">Sex</dt><dd class="font-semibold text-med-ink">{{ str($newborn->sex)->headline() }}</dd></div><div><dt class="text-med-muted">Birth Weight</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_weight ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Delivery Type</dt><dd class="font-semibold text-med-ink">{{ str($newborn->delivery->delivery_type ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Birth Date</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Status</dt><dd><x-ui.badge variant="{{ $newborn->status === 'alive' ? 'success' : 'danger' }}">{{ str($newborn->status)->headline() }}</x-ui.badge></dd></div></dl></x-ui.card>
        <div class="grid gap-4 md:grid-cols-4"><x-ui.card><p class="text-sm text-med-muted">Total Examinations</p><p class="mt-2 text-2xl font-semibold text-med-ink">{{ $examinations->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Normal</p><p class="mt-2 text-2xl font-semibold text-med-success">{{ $examinations->where('exam_status', 'normal')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Follow-up Needed</p><p class="mt-2 text-2xl font-semibold text-med-warning">{{ $examinations->where('exam_status', 'needs_follow_up')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Referral Needed</p><p class="mt-2 text-2xl font-semibold text-med-danger">{{ $examinations->where('exam_status', 'referral_needed')->count() }}</p></x-ui.card></div>
        <x-ui.card title="Examination Timeline" subtitle="{{ $examinations->count() }} records">
            <div class="divide-y divide-med-line">@forelse($examinations as $examination)<article class="py-4 first:pt-0 last:pb-0"><div class="grid gap-4 lg:grid-cols-[160px_160px_1fr_140px_auto] lg:items-start"><div><p class="text-xs uppercase text-med-muted">Examination Date</p><p class="font-semibold text-med-ink">{{ $examination->examination_date_time?->format('M d, Y') ?? 'N/A' }}</p><p class="text-sm text-med-muted">{{ $examination->examination_date_time?->format('h:i A') }}</p></div><div><p class="text-xs uppercase text-med-muted">Status</p><x-ui.badge variant="{{ $examination->exam_status === 'normal' ? 'success' : ($examination->exam_status === 'abnormal' ? 'danger' : 'warning') }}">{{ str($examination->exam_status)->headline() }}</x-ui.badge></div><div class="text-sm text-med-muted"><span class="font-medium text-med-ink">Vitals:</span> Temp {{ $examination->temperature ?? 'N/A' }}, HR {{ $examination->heart_rate ?? 'N/A' }} bpm, RR {{ $examination->respiratory_rate ?? 'N/A' }}<br><span class="font-medium text-med-ink">Feeding:</span> {{ str($examination->feeding_type ?? 'N/A')->headline() }}@if($examination->clinical_summary)<p class="mt-2 text-med-ink">{{ Str::limit($examination->clinical_summary, 250) }}</p>@endif @if($examination->next_follow_up_date)<p class="mt-2 font-medium text-med-warning">Next follow-up: {{ $examination->next_follow_up_date?->format('M d, Y h:i A') }}</p>@endif</div><div><p class="text-xs uppercase text-med-muted">Recorded By</p><p class="font-semibold text-med-ink">{{ $examination->recordedBy->name ?? 'N/A' }}</p></div><div class="flex justify-end gap-2"><a href="{{ route('midwife.newborn-examination.show', $examination) }}" class="text-sm font-semibold text-med-primary hover:text-med-primaryDark">View</a><a href="{{ route('midwife.newborn-examination.edit', $examination) }}" class="text-sm font-semibold text-med-info hover:text-blue-700">Edit</a></div></div></article>@empty<x-ui.empty-state title="No examination records found" message="No newborn examinations have been recorded yet." /><div class="mt-4 text-center"><a href="{{ route('midwife.newborn-examination.create', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Record First Examination</a></div>@endforelse</div>
        </x-ui.card>
    </div>
</x-ui.page>
@endsection
