@extends('layouts.modern')

@section('title', 'Newborn Examination Details')

@section('content')
@php
    $newborn = $newbornExamination->newborn;
    $statusVariant = $newbornExamination->exam_status === 'normal' ? 'success' : ($newbornExamination->exam_status === 'abnormal' ? 'danger' : 'warning');
@endphp
<x-ui.page title="Newborn Examination Details" subtitle="Examination for {{ $newborn->newborn_registration_number ?? 'N/A' }}.">
    <x-slot name="actions"><a href="{{ route('midwife.newborn-examination.edit', $newbornExamination) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Edit</a><a href="{{ route('midwife.newborn-examination.record', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6">
        <x-ui.card title="Examination Summary"><dl class="grid gap-4 text-sm md:grid-cols-4"><div><dt class="text-med-muted">Examination Date</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->examination_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Hours After Birth</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->hours_after_birth ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Exam Status</dt><dd><x-ui.badge variant="{{ $statusVariant }}">{{ str($newbornExamination->exam_status)->headline() }}</x-ui.badge></dd></div><div><dt class="text-med-muted">Recorded By</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->recordedBy->name ?? 'N/A' }}</dd></div></dl></x-ui.card>
        <div class="grid gap-4 md:grid-cols-4">@foreach(['temperature'=>'Temperature','heart_rate'=>'Heart Rate','respiratory_rate'=>'Respiratory Rate','weight'=>'Weight','length'=>'Length','head_circumference'=>'Head Circumference','chest_circumference'=>'Chest Circumference'] as $field=>$label)<x-ui.card><p class="text-xs uppercase text-med-muted">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-med-ink">{{ $newbornExamination->{$field} ?? 'N/A' }}</p></x-ui.card>@endforeach</div>
        <x-ui.card title="System Examination"><dl class="grid gap-4 text-sm md:grid-cols-2">@foreach(['general_appearance'=>'General Appearance','skin_examination'=>'Skin Examination','head_and_neck'=>'Head And Neck','eyes_examination'=>'Eyes Examination','ear_examination'=>'Ear Examination','mouth_and_throat'=>'Mouth And Throat','heart_sounds'=>'Heart Sounds','pulses'=>'Pulses','capillary_refill'=>'Capillary Refill','chest_expansion'=>'Chest Expansion','breath_sounds'=>'Breath Sounds','nasal_breathing'=>'Nasal Breathing','abdomen_shape'=>'Abdomen Shape','umbilical_cord_check'=>'Umbilical Cord Check','hepatomegaly_splenomegaly'=>'Hepatomegaly / Splenomegaly','bowel_sounds'=>'Bowel Sounds','genitalia_examination'=>'Genitalia Examination','urinary_output'=>'Urinary Output','stool_output'=>'Stool Output','reflex_assessment'=>'Reflex Assessment','muscle_tone'=>'Muscle Tone','developmental_screening'=>'Developmental Screening','extremities_examination'=>'Extremities Examination','hip_examination'=>'Hip Examination','spine_examination'=>'Spine Examination'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $newbornExamination->{$field} ?: 'N/A' }}</dd></div>@endforeach</dl></x-ui.card>
        <x-ui.card title="Findings And Follow-up"><dl class="grid gap-4 text-sm md:grid-cols-2"><div><dt class="font-medium text-med-muted">Jaundice Present</dt><dd><x-ui.badge variant="{{ $newbornExamination->jaundice_present ? 'warning' : 'success' }}">{{ $newbornExamination->jaundice_present ? 'Yes' : 'No' }}</x-ui.badge></dd></div>@foreach(['abnormal_findings'=>'Abnormal Findings','congenital_anomalies'=>'Congenital Anomalies','jaundice_level'=>'Jaundice Level','jaundice_management'=>'Jaundice Management','feeding_type'=>'Feeding Type','feeding_tolerance'=>'Feeding Tolerance','feeding_challenges'=>'Feeding Challenges','clinical_summary'=>'Clinical Summary','follow_up_plans'=>'Follow-up Plans'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $newbornExamination->{$field} ?: 'N/A' }}</dd></div>@endforeach<div><dt class="font-medium text-med-muted">Next Follow-up Date</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->next_follow_up_date?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div></dl></x-ui.card>
        <x-ui.card title="Record Metadata"><dl class="grid gap-4 text-sm md:grid-cols-3"><div><dt class="text-med-muted">Created At</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->created_at?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Last Updated</dt><dd class="font-semibold text-med-ink">{{ $newbornExamination->updated_at?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Examination ID</dt><dd class="font-semibold text-med-ink">#{{ $newbornExamination->id }}</dd></div></dl></x-ui.card>
    </div>
</x-ui.page>
@endsection
