@php
    $record = $childFollowUp ?? null;
    $newborn = $newborn ?? $record?->newborn;
    $patient = $newborn?->patient ?? $record?->patient;
    $fieldClass = 'mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm placeholder:text-med-muted/70';
    $labelClass = 'mb-1 block text-sm font-medium text-med-ink';
    $value = fn ($name, $default = '') => old($name, data_get($record, $name, $default));
    $dateValue = fn ($name, $default = null) => old($name, data_get($record, $name)?->format('Y-m-d\TH:i') ?? $default);
@endphp
@if ($errors->any())<div class="rounded-md border border-med-danger/25 bg-red-50 px-4 py-3 text-sm text-med-danger"><p class="font-semibold">Please fix the highlighted errors.</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 xl:grid-cols-12"><div class="space-y-6 xl:col-span-8">
<x-ui.card title="Follow-up Details"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Follow-up Date & Time</span><input type="datetime-local" name="follow_up_date_time" value="{{ $dateValue('follow_up_date_time', now()->format('Y-m-d\TH:i')) }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Days Of Life</span><input type="number" min="0" name="days_of_life" value="{{ $value('days_of_life') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Follow-up Period</span><select name="follow_up_period" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['day_3'=>'Day 3','day_7'=>'Day 7','day_10'=>'Day 10','day_14'=>'Day 14','6weeks'=>'6 Weeks','3months'=>'3 Months','6months'=>'6 Months','year1'=>'Year 1'] as $key=>$label)<option value="{{ $key }}" @selected($value('follow_up_period')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Location</span><select name="location" class="{{ $fieldClass }}">@foreach(['hospital'=>'Hospital','clinic'=>'Clinic','home'=>'Home','other'=>'Other'] as $key=>$label)<option value="{{ $key }}" @selected($value('location','hospital')===$key)>{{ $label }}</option>@endforeach</select></label><label class="md:col-span-2"><span class="{{ $labelClass }}">Location Details</span><input type="text" name="location_details" value="{{ $value('location_details') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Health Status</span><select name="health_status" class="{{ $fieldClass }}">@foreach(['normal'=>'Normal','at_risk'=>'At Risk','needs_referral'=>'Needs Referral','referred'=>'Referred'] as $key=>$label)<option value="{{ $key }}" @selected($value('health_status','normal')===$key)>{{ $label }}</option>@endforeach</select></label></div></x-ui.card>
<x-ui.card title="Feeding"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Feeding Type</span><select name="feeding_type" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['exclusive_breastfeeding'=>'Exclusive Breastfeeding','formula'=>'Formula','mixed'=>'Mixed','complementary_feeding'=>'Complementary Feeding'] as $key=>$label)<option value="{{ $key }}" @selected($value('feeding_type')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Feeding Frequency</span><input type="text" name="feeding_frequency" value="{{ $value('feeding_frequency') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Feeding Duration</span><input type="text" name="feeding_duration" value="{{ $value('feeding_duration') }}" class="{{ $fieldClass }}"></label>@foreach(['how_baby_is_feeding'=>'How Baby Is Feeding','feeding_problems'=>'Feeding Problems','latching_quality'=>'Latching Quality','suckling_pattern'=>'Suckling Pattern'] as $name=>$label)<label class="md:col-span-3"><span class="{{ $labelClass }}">{{ $label }}</span><textarea name="{{ $name }}" rows="2" class="{{ $fieldClass }}">{{ $value($name) }}</textarea></label>@endforeach</div></x-ui.card>
<x-ui.card title="Vitals And Growth"><div class="grid gap-4 md:grid-cols-4">@foreach(['temperature'=>'Temperature','heart_rate'=>'Heart Rate','respiratory_rate'=>'Respiratory Rate','weight'=>'Weight','length'=>'Length','head_circumference'=>'Head Circumference','weight_percentile'=>'Weight Percentile'] as $name=>$label)<label><span class="{{ $labelClass }}">{{ $label }}</span><input type="number" step="0.1" name="{{ $name }}" value="{{ $value($name) }}" class="{{ $fieldClass }}"></label>@endforeach</div></x-ui.card>
<x-ui.card title="Jaundice And Screening"><div class="grid gap-4 md:grid-cols-2">@foreach(['jaundice_present'=>'Jaundice Present','immunizations_up_to_date'=>'Immunizations Up To Date','newborn_screening_done'=>'Newborn Screening Done','hearing_screening_done'=>'Hearing Screening Done','danger_signs_explained'=>'Danger Signs Explained'] as $name=>$label)<label class="flex items-center gap-2 text-sm font-medium text-med-ink"><input type="checkbox" name="{{ $name }}" value="1" class="rounded border-med-line text-med-primary focus:ring-med-primary" @checked((bool) $value($name))> {{ $label }}</label>@endforeach<label><span class="{{ $labelClass }}">Jaundice Level</span><textarea name="jaundice_level" rows="2" class="{{ $fieldClass }}">{{ $value('jaundice_level') }}</textarea></label><label><span class="{{ $labelClass }}">Jaundice Management</span><textarea name="jaundice_management" rows="2" class="{{ $fieldClass }}">{{ $value('jaundice_management') }}</textarea></label><label><span class="{{ $labelClass }}">Immunizations Given</span><textarea name="immunizations_given" rows="2" class="{{ $fieldClass }}">{{ $value('immunizations_given') }}</textarea></label><label><span class="{{ $labelClass }}">Immunizations Planned</span><textarea name="immunizations_planned" rows="2" class="{{ $fieldClass }}">{{ $value('immunizations_planned') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Clinical Plan"><div class="grid gap-4 md:grid-cols-2"><label class="md:col-span-2"><span class="{{ $labelClass }}">Clinical Summary</span><textarea name="clinical_summary" rows="4" class="{{ $fieldClass }}">{{ $value('clinical_summary') }}</textarea></label><label><span class="{{ $labelClass }}">Management Plan</span><textarea name="management_plan" rows="3" class="{{ $fieldClass }}">{{ $value('management_plan') }}</textarea></label><label><span class="{{ $labelClass }}">Referral Reason</span><textarea name="referral_reason" rows="3" class="{{ $fieldClass }}">{{ $value('referral_reason') }}</textarea></label><label><span class="{{ $labelClass }}">Next Follow-up Date</span><input type="datetime-local" name="next_follow_up_date" value="{{ $dateValue('next_follow_up_date') }}" class="{{ $fieldClass }}"></label></div></x-ui.card>
</div><aside class="space-y-6 xl:col-span-4"><x-ui.card title="Child Context"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Registration #</dt><dd class="font-semibold text-med-ink">{{ $newborn?->newborn_registration_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Mother</dt><dd class="font-semibold text-med-ink">{{ $patient?->name() ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Sex</dt><dd class="font-semibold text-med-ink">{{ str($newborn?->sex ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Birth Date</dt><dd class="font-semibold text-med-ink">{{ $newborn?->birth_date_time?->format('M d, Y') ?? 'N/A' }}</dd></div></dl></x-ui.card><x-ui.card title="Save Follow-up"><div class="flex flex-col gap-2"><x-ui.button type="submit">{{ $submitLabel ?? 'Save Follow-up' }}</x-ui.button><a href="{{ $cancelRoute ?? route('midwife.child-follow-up.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Cancel</a></div></x-ui.card></aside></div>
