@extends('layouts.modern')

@section('title', 'Child Follow-up Records')

@section('content')
<x-ui.page title="Child Follow-up Records" subtitle="Search and manage child follow-up assessments.">
    <x-slot name="actions"><a href="{{ route('midwife.child-follow-up-management') }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Direct Entry</a></x-slot>
    <div class="space-y-6"><x-ui.card><form method="GET" action="{{ route('midwife.child-follow-up.index') }}" class="grid gap-3 md:grid-cols-[1fr_auto] md:items-end"><label><span class="mb-1 block text-sm font-medium text-med-ink">Search</span><input type="search" name="q" value="{{ $search }}" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm placeholder:text-med-muted/70" placeholder="Hospital number, mother, phone, period, or health status"></label><x-ui.button type="submit">Search</x-ui.button></form></x-ui.card><x-ui.card title="Records" subtitle="Total: {{ $childFollowUps->count() }}">@if($childFollowUps->isEmpty())<x-ui.empty-state title="No child follow-up records found" message="Try another search term or record a follow-up from a newborn record." />@else<x-ui.table><thead class="bg-med-canvas text-left text-xs font-semibold uppercase text-med-muted"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Hospital #</th><th class="px-4 py-3">Mother</th><th class="px-4 py-3">Newborn #</th><th class="px-4 py-3">Period</th><th class="px-4 py-3">Weight</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-med-line bg-white">@foreach($childFollowUps as $record)@php($patient = $record->patient)<tr><td class="px-4 py-4 text-med-muted">{{ $record->follow_up_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</td><td class="px-4 py-4 font-semibold text-med-ink">{{ $patient?->hospital_number ?? 'N/A' }}</td><td class="px-4 py-4 text-med-muted">{{ $patient?->name() ?? 'N/A' }}</td><td class="px-4 py-4 text-med-muted">{{ $record->newborn?->newborn_registration_number ?? 'N/A' }}</td><td class="px-4 py-4 text-med-muted">{{ str($record->follow_up_period ?? 'N/A')->headline() }}</td><td class="px-4 py-4 text-med-muted">{{ $record->weight ?? 'N/A' }}</td><td class="px-4 py-4"><x-ui.badge variant="{{ $record->health_status === 'normal' ? 'success' : ($record->health_status === 'at_risk' ? 'warning' : 'danger') }}">{{ str($record->health_status)->headline() }}</x-ui.badge></td><td class="px-4 py-4"><div class="flex flex-wrap justify-end gap-2"><a href="{{ route('midwife.child-follow-up.show', $record) }}" class="text-sm font-semibold text-med-primary hover:text-med-primaryDark">View</a><a href="{{ route('midwife.child-follow-up.edit', $record) }}" class="text-sm font-semibold text-med-info hover:text-blue-700">Edit</a>@if($patient)<a href="{{ route('midwife.patient.show', $patient) }}" class="text-sm font-semibold text-med-muted hover:text-med-ink">Profile</a>@endif</div></td></tr>@endforeach</tbody></x-ui.table>@endif</x-ui.card></div>
</x-ui.page>
@endsection
