@extends('layouts.modern')

@section('title', 'Child Follow-up Records')

@section('content')
<x-ui.page title="Child Follow-up Records" subtitle="Baby {{ $newborn->newborn_registration_number ?? 'N/A' }} - Mother: {{ $newborn->patient->name() }}">
    <x-slot name="actions"><a href="{{ route('midwife.child-follow-up.create', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">New Follow-up</a><a href="{{ route('midwife.newborn.show', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6"><x-ui.card title="Child Summary"><dl class="grid gap-4 text-sm md:grid-cols-4"><div><dt class="text-med-muted">Registration Number</dt><dd class="font-semibold text-med-ink">{{ $newborn->newborn_registration_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Sex</dt><dd class="font-semibold text-med-ink">{{ str($newborn->sex)->headline() }}</dd></div><div><dt class="text-med-muted">Birth Weight</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_weight ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Date of Birth</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_date_time?->format('M d, Y') ?? 'N/A' }}</dd></div></dl></x-ui.card>
    <div class="grid gap-4 md:grid-cols-4"><x-ui.card><p class="text-sm text-med-muted">Total Follow-ups</p><p class="mt-2 text-2xl font-semibold text-med-ink">{{ $childFollowUps->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Normal</p><p class="mt-2 text-2xl font-semibold text-med-success">{{ $childFollowUps->where('health_status', 'normal')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">At Risk</p><p class="mt-2 text-2xl font-semibold text-med-warning">{{ $childFollowUps->where('health_status', 'at_risk')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Referrals</p><p class="mt-2 text-2xl font-semibold text-med-danger">{{ $childFollowUps->whereIn('health_status', ['needs_referral', 'referred'])->count() }}</p></x-ui.card></div>
    <x-ui.card title="Follow-up Timeline" subtitle="{{ $childFollowUps->count() }} records"><div class="divide-y divide-med-line">@forelse($childFollowUps as $followUp)<article class="py-4 first:pt-0 last:pb-0"><div class="grid gap-4 lg:grid-cols-[160px_150px_150px_1fr_auto]"><div><p class="text-xs uppercase text-med-muted">Follow-up Date</p><p class="font-semibold text-med-ink">{{ $followUp->follow_up_date_time?->format('M d, Y') ?? 'N/A' }}</p><p class="text-sm text-med-muted">{{ $followUp->follow_up_date_time?->format('h:i A') }}</p></div><div><p class="text-xs uppercase text-med-muted">Stage</p><x-ui.badge>{{ str($followUp->follow_up_period ?? 'N/A')->headline() }}</x-ui.badge><p class="mt-1 text-sm text-med-muted">{{ $followUp->days_of_life ?? 'N/A' }} days old</p></div><div><p class="text-xs uppercase text-med-muted">Health Status</p><x-ui.badge variant="{{ $followUp->health_status === 'normal' ? 'success' : ($followUp->health_status === 'at_risk' ? 'warning' : 'danger') }}">{{ str($followUp->health_status)->headline() }}</x-ui.badge></div><div class="text-sm text-med-muted"><span class="font-medium text-med-ink">Vitals:</span> Temp {{ $followUp->temperature ?? 'N/A' }}, HR {{ $followUp->heart_rate ?? 'N/A' }} bpm<br><span class="font-medium text-med-ink">Growth:</span> Weight {{ $followUp->weight ?? 'N/A' }}, Length {{ $followUp->length ?? 'N/A' }}@if($followUp->clinical_summary)<p class="mt-2 text-med-ink">{{ Str::limit($followUp->clinical_summary, 260) }}</p>@endif @if($followUp->next_follow_up_date)<p class="mt-2 font-medium text-med-warning">Next follow-up: {{ $followUp->next_follow_up_date?->format('M d, Y') }}</p>@endif</div><div class="flex justify-end gap-2"><a href="{{ route('midwife.child-follow-up.show', $followUp) }}" class="text-sm font-semibold text-med-primary hover:text-med-primaryDark">View</a><a href="{{ route('midwife.child-follow-up.edit', $followUp) }}" class="text-sm font-semibold text-med-info hover:text-blue-700">Edit</a></div></div></article>@empty<x-ui.empty-state title="No follow-up records found" message="No child follow-up assessments have been recorded yet." />@endforelse</div></x-ui.card></div>
</x-ui.page>
@endsection
