@extends('layouts.modern')

@section('title', 'Child Follow-up Details')

@section('content')
@php($newborn = $childFollowUp->newborn)
<x-ui.page title="Child Follow-up Details" subtitle="Baby {{ $newborn->newborn_registration_number ?? 'N/A' }} - Mother: {{ $childFollowUp->patient?->name() ?? $newborn->patient?->name() ?? 'N/A' }}">
    <x-slot name="actions"><a href="{{ route('midwife.child-follow-up.edit', $childFollowUp) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Edit</a><a href="{{ route('midwife.child-follow-up.record', $newborn) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6"><div class="grid gap-4 md:grid-cols-4"><x-ui.card><p class="text-xs uppercase text-med-muted">Follow-up Period</p><p class="mt-2 text-lg font-semibold text-med-primary">{{ str($childFollowUp->follow_up_period ?? 'N/A')->headline() }}</p></x-ui.card><x-ui.card><p class="text-xs uppercase text-med-muted">Days Of Life</p><p class="mt-2 text-lg font-semibold text-med-ink">{{ $childFollowUp->days_of_life ?? 'N/A' }}</p></x-ui.card><x-ui.card><p class="text-xs uppercase text-med-muted">Weight</p><p class="mt-2 text-lg font-semibold text-med-ink">{{ $childFollowUp->weight ?? 'N/A' }}</p></x-ui.card><x-ui.card><p class="text-xs uppercase text-med-muted">Health Status</p><x-ui.badge variant="{{ $childFollowUp->health_status === 'normal' ? 'success' : ($childFollowUp->health_status === 'at_risk' ? 'warning' : 'danger') }}">{{ str($childFollowUp->health_status)->headline() }}</x-ui.badge></x-ui.card></div>
    <x-ui.card title="Follow-up Information"><dl class="grid gap-4 text-sm md:grid-cols-3"><div><dt class="text-med-muted">Follow-up Date</dt><dd class="font-semibold text-med-ink">{{ $childFollowUp->follow_up_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Location</dt><dd class="font-semibold text-med-ink">{{ str($childFollowUp->location ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Recorded By</dt><dd class="font-semibold text-med-ink">{{ $childFollowUp->recordedBy->name ?? 'N/A' }}</dd></div><div class="md:col-span-3"><dt class="text-med-muted">Location Details</dt><dd class="font-semibold text-med-ink">{{ $childFollowUp->location_details ?: 'N/A' }}</dd></div></dl></x-ui.card>
    <x-ui.card title="Feeding, Vitals And Growth"><dl class="grid gap-4 text-sm md:grid-cols-3">@foreach(['feeding_type'=>'Feeding Type','feeding_frequency'=>'Feeding Frequency','feeding_duration'=>'Feeding Duration','how_baby_is_feeding'=>'How Baby Is Feeding','feeding_problems'=>'Feeding Problems','latching_quality'=>'Latching Quality','suckling_pattern'=>'Suckling Pattern','temperature'=>'Temperature','heart_rate'=>'Heart Rate','respiratory_rate'=>'Respiratory Rate','length'=>'Length','head_circumference'=>'Head Circumference','weight_percentile'=>'Weight Percentile'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $childFollowUp->{$field} ?: 'N/A' }}</dd></div>@endforeach</dl></x-ui.card>
    <x-ui.card title="Jaundice, Screening And Plan"><dl class="grid gap-4 text-sm md:grid-cols-2">@foreach(['jaundice_present'=>'Jaundice Present','immunizations_up_to_date'=>'Immunizations Up To Date','newborn_screening_done'=>'Newborn Screening Done','hearing_screening_done'=>'Hearing Screening Done','danger_signs_explained'=>'Danger Signs Explained'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd><x-ui.badge variant="{{ $childFollowUp->{$field} ? 'success' : 'danger' }}">{{ $childFollowUp->{$field} ? 'Yes' : 'No' }}</x-ui.badge></dd></div>@endforeach @foreach(['jaundice_level'=>'Jaundice Level','jaundice_management'=>'Jaundice Management','immunizations_given'=>'Immunizations Given','immunizations_planned'=>'Immunizations Planned','clinical_summary'=>'Clinical Summary','management_plan'=>'Management Plan','referral_reason'=>'Referral Reason'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $childFollowUp->{$field} ?: 'N/A' }}</dd></div>@endforeach<div><dt class="font-medium text-med-muted">Next Follow-up</dt><dd class="font-semibold text-med-ink">{{ $childFollowUp->next_follow_up_date?->format('M d, Y h:i A') ?? 'Not Scheduled' }}</dd></div></dl></x-ui.card>
    <x-ui.card title="Child Information"><dl class="grid gap-4 text-sm md:grid-cols-4"><div><dt class="text-med-muted">Sex</dt><dd class="font-semibold text-med-ink">{{ str($newborn->sex)->headline() }}</dd></div><div><dt class="text-med-muted">Birth Weight</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_weight ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Birth Date</dt><dd class="font-semibold text-med-ink">{{ $newborn->birth_date_time?->format('M d, Y') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Recorded</dt><dd class="font-semibold text-med-ink">{{ $childFollowUp->created_at?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div></dl></x-ui.card></div>
</x-ui.page>
@endsection
