@php
    $row = 1;
@endphp

{{-- Report Header --}}
Daily Activity Report
@php $row += 2; @endphp

Report Date:,{{ \Carbon\Carbon::parse($reportData['date'])->format('l, F j, Y') }}
Generated By:,{{ auth()->user()->name }}
Generated At:,{{ now()->format('M d, Y H:i:s') }}
User Roles:,{{ implode(', ', array_map(function($role) { return ucfirst(str_replace('_', ' ', $role)); }, $reportData['user_roles'])) }}

@php $row += 6; @endphp

@if(empty($reportData['sections']))
No activities were recorded for the selected date or you don't have assigned roles.
@else
    @foreach($reportData['sections'] as $role => $data)
{{ ucfirst(str_replace('_', ' ', $role)) }} Activities Summary
@php $row += 2; @endphp

        @switch($role)
            @case('accountant')
Payments Recorded:,{{ $data['payments_recorded'] }}
Bills Created:,{{ $data['bills_created'] }}
Total Payment Amount:,$ {{ number_format($data['total_payment_amount'], 2) }}
Total Bill Amount:,$ {{ number_format($data['total_bill_amount'], 2) }}

                @if(!empty($data['payments']))
@php $row += 3; @endphp
Payment Details
Patient,Amount,Method,Time
                    @foreach($data['payments'] as $payment)
{{ $payment->patient->name ?? 'N/A' }},$ {{ number_format($payment->amount, 2) }},{{ $payment->payment_method }},{{ $payment->created_at->format('H:i') }}
                    @endforeach
                @endif

                @if(!empty($data['bills']))
@php $row += 2; @endphp
Bill Details
Patient,Total Amount,Status,Time
                    @foreach($data['bills'] as $bill)
{{ $bill->patient->name ?? 'N/A' }},$ {{ number_format($bill->total_amount, 2) }},{{ ucfirst($bill->status) }},{{ $bill->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('record_officer')
Visits Registered:,{{ $data['patient_visits_registered'] }}
Bills Created:,{{ $data['bills_created'] }}
Service Requests Created:,{{ $data['service_requests_created'] }}
Investigation Requests Created:,{{ $data['investigation_requests_created'] }}

                @if(!empty($data['patient_visits']))
@php $row += 3; @endphp
Patient Visits
Patient,Visit Type,Department,Time
                    @foreach($data['patient_visits'] as $visit)
{{ $visit->patient->name ?? 'N/A' }},{{ $visit->visit_type }},{{ $visit->department->name ?? 'N/A' }},{{ $visit->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('doctor')
Consultations:,{{ $data['consultations'] }}
Investigation Requests Ordered:,{{ $data['investigation_requests_ordered'] }}
Service Requests Ordered:,{{ $data['service_requests_ordered'] }}

                @if(!empty($data['consultations_list']))
@php $row += 3; @endphp
Consultation Details
Patient,Diagnosis,Treatment,Time
                    @foreach($data['consultations_list'] as $consultation)
{{ $consultation->patient->name ?? 'N/A' }},{{ $consultation->diagnosis ?? 'N/A' }},{{ $consultation->treatment ?? 'N/A' }},{{ $consultation->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('nurse')
Patients Attended:,{{ $data['patients_attended'] }}
Vital Signs Recorded:,{{ $data['vital_signs_recorded'] }}

                @if(!empty($data['vital_signs']))
@php $row += 3; @endphp
Vital Signs Recorded
Patient,Blood Pressure,Temperature,Pulse,Time
                    @foreach($data['vital_signs'] as $vital)
{{ $vital->patient->name ?? 'N/A' }},{{ $vital->blood_pressure ?? 'N/A' }},{{ $vital->temperature ?? 'N/A' }}°C,{{ $vital->pulse ?? 'N/A' }} bpm,{{ $vital->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('lab_technician')
Investigations Completed:,{{ $data['investigations_completed'] }}
Investigations Pending:,{{ $data['investigations_pending'] }}

                @if(!empty($data['investigations']))
@php $row += 3; @endphp
Investigation Details
Patient,Test Name,Status,Time
                    @foreach($data['investigations'] as $investigation)
{{ $investigation->patient->name ?? 'N/A' }},{{ $investigation->investigation_name }},{{ ucfirst($investigation->status) }},{{ $investigation->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('pharmacist')
Prescriptions Written:,{{ $data['prescriptions_written'] }}
Medicines Dispensed:,{{ $data['medicines_dispensed'] }}

                @if(!empty($data['prescriptions']))
@php $row += 3; @endphp
Prescription Details
Patient,Medicines,Dosage,Time
                    @foreach($data['prescriptions'] as $prescription)
{{ $prescription->patient->name ?? 'N/A' }},{{ $prescription->medicines ?? 'N/A' }},{{ $prescription->dosage ?? 'N/A' }},{{ $prescription->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break

            @case('radiologist')
Radiographs Completed:,{{ $data['radiographs_completed'] }}
Reports Written:,{{ $data['reports_written'] }}

                @if(!empty($data['radiographs']))
@php $row += 3; @endphp
Radiograph Details
Patient,Examination Type,Status,Time
                    @foreach($data['radiographs'] as $radiograph)
{{ $radiograph->patient->name ?? 'N/A' }},{{ $radiograph->examination_type }},{{ ucfirst($radiograph->status) }},{{ $radiograph->created_at->format('H:i') }}
                    @endforeach
                @endif
                @break
        @endswitch

@php $row += 5; @endphp

    @endforeach
@endif