<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Activity Report - {{ \Carbon\Carbon::parse($reportData['date'])->format('M d, Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #007bff;
            margin: 0 0 10px 0;
            font-size: 24px;
        }
        .header-info {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .header-info div {
            display: table-cell;
            width: 50%;
            vertical-align: top;
        }
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .section-header {
            background-color: #007bff;
            color: white;
            padding: 8px 12px;
            margin: -20px -20px 20px -20px;
            font-size: 16px;
            font-weight: bold;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-card {
            display: table-cell;
            width: 25%;
            text-align: center;
            padding: 10px;
            border: 1px solid #ddd;
            margin: 0 5px;
        }
        .stat-number {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .stat-label {
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-success {
            background-color: #28a745;
            color: white;
        }
        .badge-warning {
            background-color: #ffc107;
            color: black;
        }
        .badge-primary {
            background-color: #007bff;
            color: white;
        }
        .badge-info {
            background-color: #17a2b8;
            color: white;
        }
        .no-data {
            text-align: center;
            padding: 20px;
            color: #666;
            font-style: italic;
        }
        @page {
            margin: 1in;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Activity Report</h1>
        <div class="header-info">
            <div>
                <strong>Report Date:</strong> {{ \Carbon\Carbon::parse($reportData['date'])->format('l, F j, Y') }}<br>
                <strong>Generated By:</strong> {{ auth()->user()->name }}<br>
            </div>
            <div>
                <strong>Generated At:</strong> {{ now()->format('M d, Y H:i:s') }}<br>
                <strong>User Roles:</strong> {{ implode(', ', array_map(function($role) { return ucfirst(str_replace('_', ' ', $role)); }, $reportData['user_roles'])) }}<br>
            </div>
        </div>
    </div>

    @if(empty($reportData['sections']))
        <div class="no-data">
            No activities were recorded for the selected date or you don't have assigned roles.
        </div>
    @else
        @foreach($reportData['sections'] as $role => $data)
            <div class="section">
                <div class="section-header">
                    {{ ucfirst(str_replace('_', ' ', $role)) }} Activities Summary
                </div>

                @switch($role)
                    @case('accountant')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['payments_recorded'] }}</div>
                                <div class="stat-label">Payments Recorded</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['bills_created'] }}</div>
                                <div class="stat-label">Bills Created</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">${{ number_format($data['total_payment_amount'], 2) }}</div>
                                <div class="stat-label">Total Payments</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">${{ number_format($data['total_bill_amount'], 2) }}</div>
                                <div class="stat-label">Total Billed</div>
                            </div>
                        </div>

                        @if(!empty($data['payments']))
                            <h5>Payment Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Amount</th>
                                        <th>Method</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['payments'] as $payment)
                                        <tr>
                                            <td>{{ $payment->patient->name ?? 'N/A' }}</td>
                                            <td>${{ number_format($payment->amount, 2) }}</td>
                                            <td>{{ $payment->payment_method }}</td>
                                            <td>{{ $payment->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif

                        @if(!empty($data['bills']))
                            <h5>Bill Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Total Amount</th>
                                        <th>Status</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['bills'] as $bill)
                                        <tr>
                                            <td>{{ $bill->patient->name ?? 'N/A' }}</td>
                                            <td>${{ number_format($bill->total_amount, 2) }}</td>
                                            <td><span class="badge badge-{{ $bill->status == 'paid' ? 'success' : 'warning' }}">{{ ucfirst($bill->status) }}</span></td>
                                            <td>{{ $bill->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('record_officer')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['patient_visits_registered'] }}</div>
                                <div class="stat-label">Visits Registered</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['bills_created'] }}</div>
                                <div class="stat-label">Bills Created</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['service_requests_created'] }}</div>
                                <div class="stat-label">Services</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['investigation_requests_created'] }}</div>
                                <div class="stat-label">Investigations</div>
                            </div>
                        </div>

                        @if(!empty($data['patient_visits']))
                            <h5>Patient Visits</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Visit Type</th>
                                        <th>Department</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['patient_visits'] as $visit)
                                        <tr>
                                            <td>{{ $visit->patient->name ?? 'N/A' }}</td>
                                            <td>{{ $visit->visit_type }}</td>
                                            <td>{{ $visit->department->name ?? 'N/A' }}</td>
                                            <td>{{ $visit->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('doctor')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['consultations'] }}</div>
                                <div class="stat-label">Consultations</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['investigation_requests_ordered'] }}</div>
                                <div class="stat-label">Investigations Ordered</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['service_requests_ordered'] }}</div>
                                <div class="stat-label">Services Ordered</div>
                            </div>
                        </div>

                        @if(!empty($data['consultations_list']))
                            <h5>Consultation Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Diagnosis</th>
                                        <th>Treatment</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['consultations_list'] as $consultation)
                                        <tr>
                                            <td>{{ $consultation->patient->name ?? 'N/A' }}</td>
                                            <td>{{ $consultation->diagnosis ?? 'N/A' }}</td>
                                            <td>{{ $consultation->treatment ?? 'N/A' }}</td>
                                            <td>{{ $consultation->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('nurse')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['patients_attended'] }}</div>
                                <div class="stat-label">Patients Attended</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['vital_signs_recorded'] }}</div>
                                <div class="stat-label">Vital Signs Recorded</div>
                            </div>
                        </div>

                        @if(!empty($data['vital_signs']))
                            <h5>Vital Signs Recorded</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Blood Pressure</th>
                                        <th>Temperature</th>
                                        <th>Pulse</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['vital_signs'] as $vital)
                                        <tr>
                                            <td>{{ $vital->patient->name ?? 'N/A' }}</td>
                                            <td>{{ $vital->blood_pressure ?? 'N/A' }}</td>
                                            <td>{{ $vital->temperature ?? 'N/A' }}°C</td>
                                            <td>{{ $vital->pulse ?? 'N/A' }} bpm</td>
                                            <td>{{ $vital->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('lab_technician')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['investigations_completed'] }}</div>
                                <div class="stat-label">Investigations Completed</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['investigations_pending'] }}</div>
                                <div class="stat-label">Investigations Pending</div>
                            </div>
                        </div>

                        @if(!empty($data['investigations']))
                            <h5>Investigation Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Test Name</th>
                                        <th>Status</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['investigations'] as $investigation)
                                        <tr>
                                            <td>{{ $investigation->patient->name ?? 'N/A' }}</td>
                                        <td>{{ $investigation->investigation_name }}</td>
                                        <td><span class="badge badge-{{ $investigation->status == 'completed' ? 'success' : 'warning' }}">{{ ucfirst($investigation->status) }}</span></td>
                                        <td>{{ $investigation->created_at->format('H:i') }}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('pharmacist')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['prescriptions_written'] }}</div>
                                <div class="stat-label">Prescriptions Written</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['medicines_dispensed'] }}</div>
                                <div class="stat-label">Medicines Dispensed</div>
                            </div>
                        </div>

                        @if(!empty($data['prescriptions']))
                            <h5>Prescription Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Medicines</th>
                                        <th>Dosage</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['prescriptions'] as $prescription)
                                        <tr>
                                            <td>{{ $prescription->patient->name ?? 'N/A' }}</td>
                                            <td>{{ $prescription->medicines ?? 'N/A' }}</td>
                                            <td>{{ $prescription->dosage ?? 'N/A' }}</td>
                                            <td>{{ $prescription->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break

                    @case('radiologist')
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['radiographs_completed'] }}</div>
                                <div class="stat-label">Radiographs Completed</div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-number">{{ $data['reports_written'] }}</div>
                                <div class="stat-label">Reports Written</div>
                            </div>
                        </div>

                        @if(!empty($data['radiographs']))
                            <h5>Radiograph Details</h5>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Patient</th>
                                        <th>Examination Type</th>
                                        <th>Status</th>
                                        <th>Time</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data['radiographs'] as $radiograph)
                                        <tr>
                                            <td>{{ $radiograph->patient->name ?? 'N/A' }}</td>
                                            <td>{{ $radiograph->examination_type }}</td>
                                            <td><span class="badge badge-{{ $radiograph->status == 'completed' ? 'success' : 'warning' }}">{{ ucfirst($radiograph->status) }}</span></td>
                                            <td>{{ $radiograph->created_at->format('H:i') }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @break
                @endswitch
            </div>
        @endforeach
    @endif
</body>
</html>