<x-ui.card title="Prescriptions">
@foreach($c->prescriptions as $prescription)<div class="border-b py-3"><p>{{ $prescription->created_at }} / {{ $prescription->fulfillment }} / {{ $prescription->status }} <a class="text-med-primary underline" href="{{ route('specialist.print',[$c,'prescription',$prescription->id]) }}">Print prescription</a></p>
@foreach($prescription->prescriptionItems as $item)<p>{{ $item->medicine_name ?? $item->medicine?->name }} / {{ $item->dosage }} / {{ $item->period }} / {{ $item->duration }}</p>@endforeach</div>@endforeach
@if($c->status==='in_progress' && auth()->user()->hasPermission('specialist_prescription.issue'))
<form method="POST" action="{{ route('specialist.consultations.action',[$c,'prescribe']) }}" class="mt-4 space-y-3">@csrf<input name="token" type="hidden" value="{{ old('token',(string)Str::uuid()) }}">
<x-ui.input label="Indication / diagnosis" name="diagnosis" required/><x-ui.select label="Fulfillment" name="fulfillment"><option value="external">External prescription</option>@if(app(\App\Services\PackageCapabilities::class)->available('dispensing'))<option value="internal">Internal pharmacy</option>@endif</x-ui.select>
<div id="prescription-rows"><div class="prescription-row grid gap-3 border-b py-3 md:grid-cols-3">
<x-ui.select name="items[0][medicine_id]" label="Medicine">@foreach($medicines as $medicine)<option value="{{ $medicine->id }}">{{ $medicine->name }}</option>@endforeach</x-ui.select>
<x-ui.select name="items[0][route_id]" label="Route">@foreach($routes as $route)<option value="{{ $route->id }}">{{ $route->name }}</option>@endforeach</x-ui.select>
@foreach(['dosage','period','duration'] as $field)<x-ui.input name="items[0][{{ $field }}]" label="{{ ucfirst($field) }}" required/>@endforeach
<button type="button" onclick="if(this.closest('#prescription-rows').children.length>1)this.closest('.prescription-row').remove()">Remove item</button></div></div>
<button type="button" class="text-med-primary underline" onclick="addSpecialistMedicine()">Add another medicine</button> <x-ui.button type="submit">Issue prescription</x-ui.button></form>
<script>let specialistMedicineIndex=1;function addSpecialistMedicine(){const root=document.getElementById('prescription-rows');const row=root.firstElementChild.cloneNode(true);row.querySelectorAll('[name]').forEach(el=>{el.name=el.name.replace(/items\[\d+\]/,'items['+specialistMedicineIndex+']');if(el.tagName==='INPUT')el.value='';el.removeAttribute('id')});specialistMedicineIndex++;root.appendChild(row)}</script>
@endif</x-ui.card>
<x-ui.card title="Investigations and review">
@foreach($c->investigations as $order)<div class="space-y-3 border-b py-4"><strong>{{ $order->requested_name ?? $order->investigation?->name }} / {{ $order->is_external ? 'External' : 'Internal' }} / {{ $order->status }}</strong>
<a class="text-med-primary underline" href="{{ route('specialist.print',[$c,'investigation',$order->id]) }}">Print request</a>
@foreach($results->get($order->id,collect()) as $result)<p>{{ $result->parameter?->name }}: {{ $result->value }}</p>@endforeach
@foreach($c->documents->where('investigation_request_id',$order->id) as $document)<p><a class="text-med-primary underline" href="{{ route('specialist.documents.show',$document) }}">{{ $document->name }}</a> / {{ $document->source }} / {{ $document->report_date }}</p>@endforeach
@if($order->reviewed_at)<p>Reviewed {{ $order->reviewed_at }}: {{ $order->external_summary }}</p>
@elseif(auth()->user()->hasPermission('specialist_result.review'))
@if($order->is_external)<form method="POST" enctype="multipart/form-data" action="{{ route('specialist.documents.store',$c) }}" class="grid gap-3 md:grid-cols-3">@csrf<input type="hidden" name="request_id" value="{{ $order->id }}"><x-ui.input type="file" name="document" label="External report (PDF / image, 10 MB)" accept="application/pdf,image/png,image/jpeg" required/><x-ui.input name="source" label="Report source" required/><x-ui.input type="date" name="report_date" label="Report date" required/><x-ui.button type="submit">Attach report</x-ui.button></form>@endif
<form method="POST" action="{{ route('specialist.consultations.action',[$c,'review']) }}" class="flex flex-wrap items-end gap-3">@csrf<input type="hidden" name="request_id" value="{{ $order->id }}"><x-ui.input name="summary" label="Clinical review summary" required/><x-ui.button type="submit">Record review</x-ui.button></form>
@endif</div>@endforeach
@if($c->status==='in_progress' && auth()->user()->hasPermission('specialist_investigation.request'))<form method="POST" action="{{ route('specialist.consultations.action',[$c,'investigate']) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<input name="token" type="hidden" value="{{ old('token',(string)Str::uuid()) }}">
<x-ui.select name="destination" label="Destination"><option value="external">External facility</option>@foreach(['laboratory'=>'Internal laboratory','imaging'=>'Internal imaging'] as $key=>$label)@if(app(\App\Services\PackageCapabilities::class)->available($key))<option value="{{ $key }}">{{ $label }}</option>@endif @endforeach</x-ui.select>
<x-ui.input name="name" label="Requested investigation" required/>
<x-ui.select name="investigation_id" label="Internal test (internal requests only)"><option value="">External request</option>@foreach($tests as $test)<option value="{{ $test->id }}">{{ $test->investigationType?->department?->name }} / {{ $test->name }} / {{ $test->price }}</option>@endforeach</x-ui.select>
<x-ui.input name="external_destination" label="External facility"/><x-ui.input name="clinical_diagnoses" label="Clinical question / diagnosis" required/>
<x-ui.select name="partner_id" label="Approved partner (optional)"><option value="">None</option>@foreach($partners as $partner)<option value="{{ $partner->id }}">{{ $partner->name }}</option>@endforeach</x-ui.select><x-ui.button type="submit">Request investigation</x-ui.button></form>@endif
</x-ui.card>
<x-ui.card title="Referrals">
@foreach($c->referrals as $referral)<div class="border-b py-3"><p>{{ $referral->referred_to_department }} / {{ $referral->status }} / {{ $referral->urgency }} <a class="text-med-primary underline" href="{{ route('specialist.print',[$c,'referral',$referral->id]) }}">Print referral</a></p><p>{{ $referral->reason_for_referral }}</p><p>{{ $referral->outcome }}</p>@if($referral->destination_type==='external' && in_array($referral->status,['Pending','Accepted']) && auth()->user()->hasPermission('specialist_referral.create'))<form method="POST" action="{{ route('specialist.consultations.action',[$c,'external-outcome']) }}" class="space-y-3">@csrf<input type="hidden" name="referral_id" value="{{ $referral->id }}"><x-ui.select name="status" label="Reported outcome">@if($referral->status==='Pending')<option>Accepted</option><option>Rejected</option>@else<option>Completed</option>@endif</x-ui.select><x-ui.input name="outcome" label="Source and outcome details" required/><x-ui.button type="submit">Record external outcome</x-ui.button></form>@endif @if($referral->outcome_admission_id)<p>Linked admission #{{ $referral->outcome_admission_id }}</p>@endif</div>@endforeach
@if(auth()->user()->hasPermission('specialist_referral.create'))<form method="POST" action="{{ route('specialist.consultations.action',[$c,'refer']) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<input name="token" type="hidden" value="{{ old('token',(string)Str::uuid()) }}">
<x-ui.select name="destination_type" label="Destination type"><option value="external">External facility</option><option value="specialist">Internal specialist</option>@if(app(\App\Services\PackageCapabilities::class)->available('inpatient'))<option value="hospital">Internal hospital</option>@endif @if(app(\App\Services\PackageCapabilities::class)->available('maternity'))<option value="maternity">Internal maternity</option>@endif @if(app(\App\Services\LicenseService::class)->moduleEnabled('doctor'))<option value="clinic">Internal clinic</option>@endif</x-ui.select>
<x-ui.input name="destination" label="Destination name / department" required/>
<x-ui.select name="destination_user_id" label="Receiving staff (internal only)"><option value="">External</option>@foreach($receivers as $receiver)<option value="{{ $receiver->id }}">{{ $receiver->name }}</option>@endforeach</x-ui.select>
<x-ui.select name="partner_id" label="Approved partner (optional)"><option value="">None</option>@foreach($partners as $partner)<option value="{{ $partner->id }}">{{ $partner->name }}</option>@endforeach</x-ui.select>
<x-ui.select name="urgency" label="Urgency"><option>routine</option><option>urgent</option><option>emergency</option></x-ui.select>
<x-ui.input name="reason" label="Reason / requested service" required/><label class="block">Clinical summary<textarea name="summary" class="w-full rounded-md border p-3" required></textarea></label><x-ui.button type="submit">Create referral</x-ui.button></form>@endif
</x-ui.card>
