@extends('layouts.modern')
@section('content')<x-ui.page title="Specialist Activity Report" subtitle="Scoped to assigned patients, by consultation booking date. Financial figures are for this consultation cohort, not a cashbook by payment date.">
<x-slot:actions><a href="{{ route('specialist.index') }}">Workspace</a></x-slot:actions>@include('specialist.notice')
<form method="GET" class="flex items-end gap-3"><x-ui.input type="date" name="from" label="From" value="{{ $from }}"/><x-ui.input type="date" name="to" label="To" value="{{ $to }}"/><x-ui.button type="submit">Filter</x-ui.button></form>
<div class="grid gap-4 md:grid-cols-3"><x-ui.card>Consultations <strong>{{ $rows->count() }}</strong></x-ui.card><x-ui.card>Distinct patients <strong>{{ $rows->pluck('patient_id')->unique()->count() }}</strong></x-ui.card><x-ui.card>Completed <strong>{{ $rows->where('status','completed')->count() }}</strong></x-ui.card></div>
<div class="grid gap-4 md:grid-cols-2"><x-ui.card title="Consultations by specialist">@foreach($rows->groupBy('specialist_profile_id') as $group)<p>{{ $group->first()->specialist_name }}: {{ $group->count() }}</p>@endforeach</x-ui.card>
<x-ui.card title="Consultations by specialty">@foreach($rows->groupBy('specialty_id') as $group)<p>{{ $group->first()->specialty_name }}: {{ $group->count() }}</p>@endforeach</x-ui.card></div>
<x-ui.card title="Service utilization">@foreach($rows->groupBy('service_id') as $group)<p>{{ $group->first()->service_name }}: {{ $group->count() }} bookings, {{ $group->where('status','completed')->count() }} completed</p>@endforeach</x-ui.card>
<x-ui.card title="New and returning visits"><p>New: {{ $rows->count() - $returning }} | Returning: {{ $returning }}</p><p>A returning visit has a prior completed Specialist consultation at its booking time.</p></x-ui.card>
@if($clinical)
<x-ui.card title="Follow-up and care plans"><p>Follow-up requested: {{ $rows->whereNotNull('followup_due')->count() }} | Completed: {{ $rows->filter(fn($c)=>$c->followup?->status === 'completed')->count() }} | Outstanding due: {{ $rows->filter(fn($c)=>$c->followup_due && $c->followup_due->lte(today()) && $c->followup?->status !== 'completed')->count() }} | Overdue: {{ $rows->filter(fn($c)=>$c->followup_due && $c->followup_due->lt(today()) && $c->followup?->status !== 'completed')->count() }}</p>
<p>Active care plans due for review: {{ $rows->filter(fn($c)=>$c->carePlans->first()?->status === 'active' && $c->carePlans->first()->review_date->lte(today()))->count() }}</p></x-ui.card>
<x-ui.card title="Investigation results">@php($requests=$rows->flatMap->investigations)<p>Pending: {{ $requests->whereNull('completed_at')->count() }} | Awaiting review: {{ $requests->whereNotNull('completed_at')->whereNull('reviewed_at')->count() }} | Reviewed: {{ $requests->whereNotNull('reviewed_at')->count() }}</p></x-ui.card>
<x-ui.card title="Referrals">@forelse($rows->flatMap->referrals->groupBy('referred_to_department') as $destination=>$referrals)<p>{{ $destination }}: @foreach($referrals->groupBy('status') as $status=>$group){{ $status }} {{ $group->count() }}; @endforeach</p>@empty<p>No referrals.</p>@endforelse</x-ui.card>
<x-ui.card title="Recorded diagnoses">@forelse($rows->filter(fn($c)=>filled($c->clinical['diagnosis'] ?? null))->groupBy(fn($c)=>$c->clinical['diagnosis']) as $diagnosis=>$group)<p>{{ $diagnosis }}: {{ $group->count() }}</p>@empty<p>No diagnoses recorded.</p>@endforelse</x-ui.card>
@endif
@if($revenue)@php($bills=$rows->flatMap->bills)<x-ui.card title="Cohort finances"><p>Billed: {{ number_format($bills->sum('due_amount'),2) }} | Paid: {{ number_format($bills->flatMap->payments->where('status','completed')->sum('amount'),2) }} | Outstanding: {{ number_format($bills->sum(fn($b)=>$b->balance),2) }}</p><p>Includes consultation and internal diagnostic bills linked to these consultations. Pharmacy dispensing remains in Pharmacy accounting.</p></x-ui.card>@endif
<x-ui.card title="Consultations"><x-ui.table><thead><tr><th>Date</th><th>Patient</th><th>Specialist / Specialty</th><th>Service</th><th>Status</th><th>Follow-up</th>@if($revenue)<th>Billed / Paid / Outstanding</th>@endif</tr></thead><tbody>@forelse($rows as $c)<tr><td class="p-3">{{ $c->created_at->format('Y-m-d') }}</td><td>{{ $c->patient->name() }}</td><td>{{ $c->specialist_name }} / {{ $c->specialty_name }}</td><td>{{ $c->service_name }}</td><td>{{ $c->status }}</td><td>{{ $c->followup_due?->format('Y-m-d') }}</td>@if($revenue)<td>{{ number_format($c->bills->sum('due_amount'),2) }} / {{ number_format($c->bills->flatMap->payments->where('status','completed')->sum('amount'),2) }} / {{ number_format($c->bills->sum(fn($b)=>$b->balance),2) }}</td>@endif</tr>@empty<tr><td colspan="7">No records.</td></tr>@endforelse</tbody></x-ui.table></x-ui.card>
</x-ui.page>@endsection
