{{-- Report Header --}}
<div class="card shadow-sm mb-4">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <h5><strong>Report Date:</strong> {{ $date }}</h5>
                <h5><strong>Generated By:</strong> {{ auth()->user()->name }}</h5>
            </div>
            <div class="col-md-6">
                <h5><strong>Generated At:</strong> {{ now() }}</h5>
            </div>
        </div>
    </div>
</div>