<div class="space-y-6">
    <x-ui.page title="{{ $listMode === 'deleted' ? 'Deleted Bills' : ($listMode === 'unpaid' ? 'Unpaid Bills' : ($mode === 'index' ? 'Bills Management' : ($isEditing ? 'Edit Bill' : 'Create Bill'))) }}" subtitle="{{ $listMode === 'deleted' ? 'Soft-deleted bills are shown here for restore.' : ($listMode === 'unpaid' ? 'All unpaid bills are shown here for accountant correction.' : ($mode === 'index' ? 'Bills you created today are shown here.' : 'Create or update billable services and investigations.')) }}">
        <x-slot name="actions">
            <div class="flex flex-wrap gap-2">
                @if($mode === 'index')
                    <a href="{{ route('accountant.bills.unpaid') }}" class="inline-flex items-center justify-center rounded-md border border-med-danger bg-white px-3 py-2 text-sm font-semibold text-med-danger transition hover:bg-red-50">Unpaid Bills</a>
                    <a href="{{ route('accountant.bills.deleted') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Deleted Bills</a>
                    <button type="button" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark" wire:click="createMode">New Bill</button>
                @else
                    <button type="button" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas" wire:click="indexMode">Back to Bills</button>
                @endif
            </div>
        </x-slot>

        @if($mode === 'index')
            <div class="grid gap-4 md:grid-cols-4">
                <x-ui.card><p class="text-sm text-med-muted">{{ $listMode === 'deleted' ? 'Deleted Bills' : ($listMode === 'unpaid' ? 'Unpaid Bills' : "Today's Bills") }}</p><p class="mt-2 text-2xl font-semibold text-med-ink">{{ number_format($summary['count']) }}</p></x-ui.card>
                <x-ui.card><p class="text-sm text-med-muted">Gross Amount</p><p class="mt-2 text-2xl font-semibold text-med-primary">&#8358;{{ number_format($summary['amount'], 2) }}</p></x-ui.card>
                <x-ui.card><p class="text-sm text-med-muted">Discount</p><p class="mt-2 text-2xl font-semibold text-med-warning">&#8358;{{ number_format($summary['discount'], 2) }}</p></x-ui.card>
                <x-ui.card><p class="text-sm text-med-muted">Amount Due</p><p class="mt-2 text-2xl font-semibold text-med-success">&#8358;{{ number_format($summary['due'], 2) }}</p></x-ui.card>
            </div>

            <x-ui.card title="Bill Register">
                <div class="mb-4 grid gap-3 md:grid-cols-4 md:items-end">
                    <label class="md:col-span-2"><span class="mb-1 block text-sm font-medium text-med-ink">Search</span><input type="search" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live.debounce.400ms="search" placeholder="Bill number, patient, or description"></label>
                    <label><span class="mb-1 block text-sm font-medium text-med-ink">Status</span><select class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="status"><option value="">All Status</option><option value="pending">Pending</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select></label>
                    <label><span class="mb-1 block text-sm font-medium text-med-ink">Rows</span><select class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="perPage"><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></label>
                </div>
                <x-ui.table>
                    <thead class="bg-med-canvas text-left text-xs font-semibold uppercase text-med-muted"><tr><th class="px-4 py-3">Bill</th><th class="px-4 py-3">Patient</th><th class="px-4 py-3">Description</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-right">Due</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead>
                    <tbody class="divide-y divide-med-line bg-white">@forelse($bills as $bill)@php($patient = $bill->walkinPatient?->name ?? $bill->patientVisit?->patient?->demographic?->getFullNameAttribute() ?? 'N/A')@php($hospitalNumber = $bill->walkinPatient ? 'Walk-in' : ($bill->patientVisit?->patient?->hospital_number ?? 'N/A'))<tr wire:key="bill-{{ $bill->id }}"><td class="px-4 py-4"><div class="font-semibold text-med-ink">{{ $bill->bill_number }}</div><div class="text-sm text-med-muted">{{ optional($bill->issued_date)->format('M d, Y h:i A') }}</div></td><td class="px-4 py-4"><div class="text-med-ink">{{ $patient }}</div><div class="text-sm text-med-muted">{{ $hospitalNumber }}</div></td><td class="px-4 py-4 text-med-muted">{{ $bill->service_description }}</td><td class="px-4 py-4 text-right text-med-muted">&#8358;{{ number_format($bill->amount, 2) }}</td><td class="px-4 py-4 text-right font-semibold text-med-ink">&#8358;{{ number_format($bill->due_amount, 2) }}</td><td class="px-4 py-4"><x-ui.badge variant="{{ $bill->status === 'paid' ? 'success' : ($bill->status === 'partial' ? 'warning' : ($bill->status === 'cancelled' ? 'secondary' : 'danger')) }}">{{ ucfirst($bill->status) }}</x-ui.badge></td><td class="px-4 py-4"><div class="flex justify-end gap-2">@if($listMode === 'deleted')<button type="button" class="text-sm font-semibold text-med-success hover:text-green-700" wire:click="restore({{ $bill->id }})" wire:confirm="Restore this bill?">Restore</button>@else<a href="{{ route('accountant.bills.show', $bill) }}" class="text-sm font-semibold text-med-primary hover:text-med-primaryDark">View</a>@if($bill->canBeManagedAsUnpaidByAccountant(auth()->user()))<button type="button" class="text-sm font-semibold text-med-info hover:text-blue-700" wire:click="edit({{ $bill->id }})">Edit</button><button type="button" class="text-sm font-semibold text-med-danger hover:text-red-800" wire:click="delete({{ $bill->id }})" wire:confirm="Soft delete this unpaid bill? It can be restored later.">Delete</button>@endif@endif</div></td></tr>@empty<tr><td colspan="7" class="px-4 py-8"><x-ui.empty-state title="No bill found" message="Try another filter or create a new bill." /></td></tr>@endforelse</tbody>
                </x-ui.table>
                @if($bills->hasPages())<div class="mt-4">{{ $bills->links() }}</div>@endif
            </x-ui.card>
        @else
            <form wire:submit="save" class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
                <div class="space-y-6">
                    <x-ui.card title="Patient Details">
                        @error('bill')<div class="mb-4 rounded-md border border-med-danger bg-red-50 px-4 py-3 text-sm text-med-danger">{{ $message }}</div>@enderror
                        @error('items')<div class="mb-4 rounded-md border border-med-danger bg-red-50 px-4 py-3 text-sm text-med-danger">{{ $message }}</div>@enderror
                        @if($isEditing)<div class="mb-4 rounded-md border border-med-info bg-blue-50 px-4 py-3 text-sm text-med-info">Patient details are locked for existing bills. Create a new bill if the patient was selected incorrectly.</div>@endif
                        <div class="grid gap-4 md:grid-cols-2"><label><span class="mb-1 block text-sm font-medium text-med-ink">Hospital Number</span><input type="text" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live.debounce.500ms="hospitalNumber" placeholder="Use for registered patient" @disabled($isEditing)>@error('hospitalNumber')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror @if($selectedPatient)<p class="mt-1 text-sm text-med-success">{{ $selectedPatient->demographic?->getFullNameAttribute() }} found.</p>@elseif($hospitalNumber !== '')<p class="mt-1 text-sm text-med-danger">No patient found with this hospital number.</p>@endif</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Walk-in Patient Name</span><input type="text" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="walkinName" placeholder="Use when patient is not registered" @disabled($isEditing)>@error('walkinName')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Walk-in Phone</span><input type="text" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="walkinPhone" @disabled($isEditing)>@error('walkinPhone')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Walk-in Email</span><input type="email" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="walkinEmail" @disabled($isEditing)>@error('walkinEmail')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label></div>
                    </x-ui.card>
                    <x-ui.card title="Services"><x-slot name="actions"><button type="button" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-white px-3 py-2 text-sm font-semibold text-med-primary transition hover:bg-med-canvas" wire:click="addService">Add Service</button></x-slot><div class="space-y-3">@foreach($services as $index => $serviceRow)<div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_7rem_6rem] md:items-end" wire:key="service-row-{{ $index }}"><label><span class="mb-1 block text-sm font-medium text-med-ink">Service</span><select class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="services.{{ $index }}.id"><option value="">Select service</option>@foreach($serviceGroups as $group => $groupServices)<optgroup label="{{ $group ?: 'Other' }}">@foreach($groupServices as $service)<option value="{{ $service->id }}">{{ $service->name }} - &#8358;{{ number_format($service->price, 2) }}</option>@endforeach</optgroup>@endforeach</select>@error('services.' . $index . '.id')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Qty</span><input type="number" min="1" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="services.{{ $index }}.quantity">@error('services.' . $index . '.quantity')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><button type="button" class="inline-flex items-center justify-center rounded-md border border-med-danger bg-white px-3 py-2 text-sm font-semibold text-med-danger transition hover:bg-red-50" wire:click="removeService({{ $index }})">Remove</button></div>@endforeach</div></x-ui.card>
                    <x-ui.card title="Investigations"><x-slot name="actions"><button type="button" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-white px-3 py-2 text-sm font-semibold text-med-primary transition hover:bg-med-canvas" wire:click="addInvestigation">Add Investigation</button></x-slot><div class="space-y-3">@forelse($investigations as $index => $investigationRow)<div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_7rem_6rem] md:items-end" wire:key="investigation-row-{{ $index }}"><label><span class="mb-1 block text-sm font-medium text-med-ink">Investigation</span><select class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="investigations.{{ $index }}.id"><option value="">Select investigation</option>@foreach($investigationGroups as $group => $groupInvestigations)<optgroup label="{{ $group ?: 'Other' }}">@foreach($groupInvestigations as $investigation)<option value="{{ $investigation->id }}">{{ $investigation->name }} - &#8358;{{ number_format($investigation->price, 2) }}</option>@endforeach</optgroup>@endforeach</select>@error('investigations.' . $index . '.id')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Qty</span><input type="number" min="1" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="investigations.{{ $index }}.quantity">@error('investigations.' . $index . '.quantity')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><button type="button" class="inline-flex items-center justify-center rounded-md border border-med-danger bg-white px-3 py-2 text-sm font-semibold text-med-danger transition hover:bg-red-50" wire:click="removeInvestigation({{ $index }})">Remove</button></div>@empty<x-ui.empty-state title="No investigation selected" />@endforelse</div></x-ui.card>
                </div>
                <x-ui.card title="Bill Summary" class="self-start lg:sticky lg:top-6"><div class="space-y-4"><label><span class="mb-1 block text-sm font-medium text-med-ink">Issued Date</span><input type="date" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="issuedDate" @if(! $isEditing) min="{{ today()->toDateString() }}" max="{{ today()->toDateString() }}" readonly @endif>@error('issuedDate')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Due Date</span><input type="date" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="dueDate">@error('dueDate')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label><label><span class="mb-1 block text-sm font-medium text-med-ink">Discount (%)</span><input type="number" min="0" max="100" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="discount">@error('discount')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label>@if($isEditing)<label><span class="mb-1 block text-sm font-medium text-med-ink">Status</span><select class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm" wire:model.live="billStatus"><option value="pending">Pending</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select>@error('billStatus')<p class="mt-1 text-sm text-med-danger">{{ $message }}</p>@enderror</label>@endif<div class="border-t border-med-line pt-4 text-sm"><div class="flex justify-between py-1"><span class="text-med-muted">Amount</span><strong>&#8358;{{ number_format($totals['amount'], 2) }}</strong></div><div class="flex justify-between py-1"><span class="text-med-muted">Discount</span><strong>&#8358;{{ number_format($totals['discount'], 2) }}</strong></div><div class="flex justify-between py-2 text-lg"><span class="text-med-ink">Due</span><strong>&#8358;{{ number_format($totals['due'], 2) }}</strong></div></div><button type="submit" class="inline-flex w-full items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark" wire:loading.attr="disabled" wire:target="save"><span wire:loading.remove wire:target="save">{{ $isEditing ? 'Update Bill' : 'Save Bill' }}</span><span wire:loading wire:target="save">Saving...</span></button></div></x-ui.card>
            </form>
        @endif
    </x-ui.page>
</div>
