@extends('network.layout') @section('network')<h1>{{ ucfirst($c->kind) }} collaboration</h1><p>{{ $c->uuid }} &middot; {{ $c->status }}</p><section><h2>Shared care information</h2>@foreach($disclosure->packet as $key=>$value)<p><strong>{{ str($key)->replace('_',' ')->title() }}</strong></p><pre>{{ $value }}</pre>@endforeach<p>Purpose: {{ $disclosure->purpose }}</p><small>Access expires {{ $disclosure->expires_at }} {{ $disclosure->revoked_at ? ' / REVOKED' : '' }}</small></section>
@if($portal)<details><summary>Respond or update case</summary><form method="POST" action="{{ route('partner.case.action',[$c,'respond']) }}">@csrf<input type="hidden" name="token" value="{{ (string)Str::uuid() }}"><input type="hidden" name="version" value="{{ $c->version }}"><label>Action<select name="action">@foreach(['accepted','declined','scheduled','in_progress','presented','admitted','discharged','cancelled','message'] as $action)<option>{{ $action }}</option>@endforeach</select></label><label>Occurred at<input type="datetime-local" name="occurred_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label>Outcome, appointment information or message<textarea name="message" required></textarea></label><label>Your facility reference (optional)<input name="remote_reference"></label><button>Record response</button></form></details>
@if($c->assigned_user_id===auth('partner')->id())<details><summary>Assign to a colleague</summary><form method="POST" action="{{ route('partner.case.action',[$c,'assign']) }}">@csrf<input type="hidden" name="version" value="{{ $c->version }}"><label>Colleague<select name="user_id">@foreach(\App\Models\PartnerMembership::join('users','users.id','=','partner_memberships.user_id')->where('partner_id',\App\Models\Partnership::find($c->partnership_id)->partner_id)->where('is_active',true)->whereIn('role',['intake','worker','administrator_intake'])->select('users.id','users.name')->get() as $colleague)<option value="{{ $colleague->id }}">{{ $colleague->name }}</option>@endforeach</select></label><button>Transfer assigned care</button></form></details>@endif
<details><summary>Submit report or corrected report</summary><form method="POST" action="{{ route('partner.case.action',[$c,'submit']) }}">@csrf<input type="hidden" name="token" value="{{ (string)Str::uuid() }}"><input type="hidden" name="version" value="{{ $c->version }}"><label>Findings, result, discharge information or recommendations<textarea name="content" required maxlength="30000"></textarea></label><button>Submit report version</button></form></details>
@else @if(auth()->user()->hasPermission('partner_collaboration.manage'))<form method="POST" action="{{ route('network.case.action',[$c,'revoke']) }}">@csrf<button>Revoke future partner access</button></form>@endif @endif
@if(!$portal && auth()->user()->hasPermission('partner_collaboration.manage'))<details><summary>Update authorized sharing</summary><p>The patient identity and requested service shown above remain unchanged. Only the summary below replaces the previous summary in a new disclosure version.</p><form method="POST" action="{{ route('network.case.action',[$c,'disclose']) }}">@csrf<label>Summary to share<textarea name="summary" required>{{ $disclosure->packet['summary'] }}</textarea></label><label>Purpose<input name="purpose" required value="{{ $disclosure->purpose }}"></label><label>Authorization evidence<textarea name="authorization_basis" required></textarea></label><label>Access expires<input type="datetime-local" name="expires_at" required></label><label><input type="checkbox" name="confirm_disclosure" value="1" required>I reviewed and authorize this new disclosure.</label><button>Publish disclosure version</button></form></details><details><summary>Cancel before rerouting</summary><form method="POST" action="{{ route('network.case.action',[$c,'cancel']) }}">@csrf<label>Reason<textarea name="reason" required></textarea></label><button>Cancel and revoke access</button></form></details>@endif
<section><h2>Reports and review history</h2>@forelse($submissions as $s)<h3>Version {{ $s->version }} &middot; {{ $s->created_at }}</h3><pre>{{ $s->content }}</pre>@if($s->reviewed_at)<p>Reviewed {{ $s->reviewed_at }}</p><pre>{{ $s->review }}</pre>@elseif(!$portal && $loop->first && auth()->user()->hasPermission('partner_result.receive'))<form method="POST" action="{{ route('network.case.action',[$c,'review']) }}">@csrf<input type="hidden" name="submission_id" value="{{ $s->id }}"><label>Clinical review<textarea name="review" required></textarea></label><button>Complete review</button></form>@endif @empty<p>No report submitted.</p>@endforelse</section>
<section><h2>Case events</h2>@foreach($events as $event)<p>{{ $event->action }} &middot; occurred {{ $event->occurred_at }} &middot; received {{ $event->created_at }}</p><pre>{{ $event->message }}</pre>@endforeach</section>
@include('network.documents') @endsection
