@extends('network.layout') @section('network')<h1>{{ $partner->name }}</h1><p>{{ $type->name }} &middot; {{ $p->status }} &middot; {{ $p->purpose }}</p>
@if(session('invitation_link'))<section class="notice"><strong>Invitation link - copy now and share securely with the intended recipient</strong><p style="overflow-wrap:anywhere">{{ session('invitation_link') }}</p><small>Valid for seven days. Creating this link does not confirm delivery.</small></section>@endif
@if(auth()->user()->hasPermission('partner.invite'))<details><summary>Invite partner representative</summary><form method="POST" action="{{ route('network.action',[$p,'invite']) }}">@csrf<label>Email<input type="email" name="email" required></label><label>Access<select name="role"><option value="administrator">Onboarding administrator (no clinical cases)</option><option value="intake">Clinical intake (can accept cases)</option><option value="administrator_intake">Administrator and clinical intake (explicit combined access)</option><option value="worker">Assigned case worker</option></select></label><button>Create invitation</button></form></details>@endif
<section><h2>Submitted information</h2>@if($submission)<p>Revision {{ $submission->version }} / template {{ $submission->template_version }}</p>@foreach($submission->details as $key=>$value)<p><strong>{{ str($key)->replace('_',' ')->title() }}:</strong> {{ $value }}</p>@endforeach @else<p>Awaiting partner registration.</p>@endif</section>
@if(auth()->user()->hasPermission('partner.verify') || auth()->user()->hasPermission('partner.approve') || auth()->user()->hasPermission('partnership.manage') || auth()->user()->hasPermission('partner.suspend'))<details><summary>Review or change relationship status</summary><form method="POST" action="{{ route('network.action',[$p,'transition']) }}">@csrf<input type="hidden" name="version" value="{{ $p->version }}"><label>Next state<select name="status">@foreach(['under_review','registration_submitted','approved','rejected','onboarding','active','suspended','inactive','terminated'] as $status)<option>{{ $status }}</option>@endforeach</select></label>@foreach($submission?->requirements ?? [] as $requirement)<label><input type="checkbox" name="checks[]" value="{{ $requirement }}"> {{ $requirement }}</label>@endforeach<label>Decision evidence and reason<textarea name="reason" required></textarea></label><button>Apply decision</button></form><small>Approval requires a reviewer other than the registering or submitting person. Activation requires acknowledged, current terms.</small></details>@endif
@include('network.services',['serviceAction'=>route('network.action',[$p,'service']),'canEdit'=>auth()->user()->hasPermission('partner_service.manage')])
@if($agreement)<section><h2>Latest agreement</h2><p>{{ $agreement->reference }} &middot; version {{ $agreement->version }} &middot; {{ $agreement->accepted_at ? 'Acknowledged' : 'Awaiting partner acknowledgement' }}</p><pre>{{ $agreement->terms }}</pre><p>{{ $agreement->effective_at }} &middot; {{ $agreement->expires_at }}</p></section>@endif
@if(auth()->user()->hasPermission('partnership.manage'))<details><summary>Create agreement version</summary><form method="POST" action="{{ route('network.action',[$p,'agreement']) }}">@csrf<label>Reference<input name="reference" required></label><label>Terms<textarea name="terms" required></textarea></label><label>Effective time<input name="effective_at" type="datetime-local" required></label><label>Expiry<input name="expires_at" type="datetime-local" required></label>@foreach(['diagnostic','hospital','specialist','submit_reports','exchange_documents','case_messages','update_status'] as $cap)<label><input type="checkbox" name="capabilities[]" value="{{ $cap }}">{{ str($cap)->replace('_',' ')->title() }}</label>@endforeach @foreach($services as $service)<label><input type="checkbox" name="service_ids[]" value="{{ $service->id }}">{{ $service->name }} / {{ $service->location }}</label>@endforeach<button>Create terms for acknowledgement</button></form></details>
<section><h2>Partner members</h2>@foreach($members as $m)<form method="POST" action="{{ route('network.action',[$p,'membership']) }}">@csrf<input type="hidden" name="membership_id" value="{{ $m->id }}"><p>{{ $m->name }} / {{ $m->email }} / {{ $m->role }}</p><input type="hidden" name="is_active" value="{{ $m->is_active?0:1 }}"><button>{{ $m->is_active?'Suspend membership':'Reactivate membership' }}</button></form>@endforeach</section>@endif
@if(auth()->user()->hasPermission('partner.edit'))<details><summary>Correct provider identity/contact</summary><p>Changing approved provider details returns affected relationships to review and pauses clinical access.</p><form method="POST" action="{{ route('network.action',[$p,'edit']) }}">@csrf<label>Name<input name="name" value="{{ $partner->name }}" required></label><label>Contact<input name="contact" value="{{ $partner->contact }}" required></label><label>Reason<textarea name="reason" required></textarea></label><button>Save correction and require review</button></form></details>@endif
@include('network.documents' ,['portal'=>false,'c'=>null]) @endsection
