<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patient Register</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #222; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ddd; padding: 5px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { border-bottom: 2px solid #198754; padding-bottom: 10px; margin-bottom: 12px; }
        .header td { border: 0; padding: 0; }
        .logo { width: 72px; height: 72px; object-fit: contain; }
        .hospital-name { font-size: 17px; font-weight: bold; color: #198754; }
        .report-meta { font-size: 10px; color: #555; text-align: right; }
        .summary td { width: 16.66%; }
        .muted { color: #666; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 86px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Patient Register</h1>
                <div class="muted">{{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</div>
            </td>
            <td class="report-meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Total</strong><br>{{ number_format($summary['total']) }}</td>
            <td><strong>Registered</strong><br>{{ number_format($summary['registered']) }}</td>
            <td><strong>Walk-in</strong><br>{{ number_format($summary['walk_in']) }}</td>
            <td><strong>Male</strong><br>{{ number_format($summary['male']) }}</td>
            <td><strong>Female</strong><br>{{ number_format($summary['female']) }}</td>
            <td><strong>Other</strong><br>{{ number_format($summary['other']) }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Hospital No</th>
                <th>Patient</th>
                <th>Gender</th>
                <th>Age</th>
                <th>Phone</th>
                <th>File Type</th>
                <th>Type</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @forelse($patients as $patient)
                <tr>
                    <td>{{ $patient->hospital_number }}</td>
                    <td>{{ $patient->demographic?->full_name ?? 'N/A' }}</td>
                    <td>{{ $patient->demographic?->gender ?? 'N/A' }}</td>
                    <td>{{ $patient->demographic?->age ?? 'N/A' }}</td>
                    <td>{{ $patient->demographic?->phone_number ?? 'N/A' }}</td>
                    <td>{{ $patient->fileType?->name ?? 'General file' }}</td>
                    <td>{{ $patient->is_walkIn ? 'Walk-in' : 'Registered' }}</td>
                    <td>{{ $patient->registration_date?->format('Y-m-d') ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">No patients found for this register period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
