@extends('layouts.modern')

@section('content')
    <x-ui.page title="Pharmacy Transaction" subtitle="Legacy transaction form. The Livewire transaction workspace is the primary route.">
        <form action="{{ route('pharmacy.transactions.store') }}" method="post" id="transactionForm">
            @csrf
            <input type="hidden" name="items" id="itemsInput"><input type="hidden" id="total_amount" name="total_amount" value="0">
            <div class="grid gap-6 xl:grid-cols-12">
                <x-ui.card class="xl:col-span-4" title="Add Medicine"><div class="space-y-4"><x-ui.select label="Payment Method" name="payment_method_id" required><option value="">Select Payment Method</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected(old('payment_method_id') == $method->id)>{{ $method->name }}</option>@endforeach</x-ui.select><x-ui.input label="Payment Reference" name="reference_number" value="{{ old('reference_number') }}" placeholder="Optional receipt/POS/transfer reference" /><label class="block"><span class="mb-1 block text-sm font-medium text-med-ink">Medicine</span><select id="medicineSelect" class="mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm"><option value="">Select Medicine</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" data-price="{{ $batch->selling_price }}" data-name="{{ $batch->medicine->name }}" data-stock="{{ $batch->quantity_remaining }}">{{ $batch->medicine->name }} (Stock: {{ $batch->quantity_remaining }}, Price: {{ $batch->selling_price }})</option>@endforeach</select></label><x-ui.input label="Quantity" id="quantityInput" type="number" min="1" /><x-ui.button type="button" id="addMedicineBtn"><i class="bi bi-plus-circle"></i>Add</x-ui.button></div></x-ui.card>
                <x-ui.card class="xl:col-span-8" title="Transaction Summary"><x-ui.table class="shadow-none"><thead class="bg-med-canvas text-left text-xs font-semibold uppercase text-med-muted"><tr><th class="px-4 py-3">Medicine</th><th class="px-4 py-3">Price</th><th class="px-4 py-3">Qty</th><th class="px-4 py-3">Subtotal</th><th class="px-4 py-3"></th></tr></thead><tbody id="transactionTable" class="divide-y divide-med-line bg-white"></tbody><tfoot class="bg-med-canvas"><tr><td colspan="3" class="px-4 py-3 text-right font-semibold text-med-ink">Total</td><td colspan="2" class="px-4 py-3 font-semibold text-med-ink">&#8358; <span id="totalAmount">0</span></td></tr></tfoot></x-ui.table><div class="mt-5 flex justify-end"><x-ui.button type="submit" id="submitTransactionBtn"><i class="bi bi-check-circle"></i>Proceed Payment</x-ui.button></div></x-ui.card>
            </div>
        </form>
    </x-ui.page>
    <script>let transactionItems=[];let totalAmount=0;const medicineSelect=document.getElementById('medicineSelect');const quantityInput=document.getElementById('quantityInput');const tableBody=document.getElementById('transactionTable');const totalDisplay=document.getElementById('totalAmount');document.getElementById('addMedicineBtn').addEventListener('click',function(){const selected=medicineSelect.options[medicineSelect.selectedIndex];const batchId=selected.value;const name=selected.dataset.name;const price=parseFloat(selected.dataset.price);const quantity=parseInt(quantityInput.value);const stock=parseInt(selected.dataset.stock);if(!batchId||!quantity)return;if(quantity>stock){alert(`Only ${stock} available for ${name}.`);return}const subtotal=price*quantity;transactionItems.push({batchId,name,price,quantity,subtotal});renderTable();document.getElementById('itemsInput').value=JSON.stringify(transactionItems)});function renderTable(){tableBody.innerHTML='';totalAmount=0;transactionItems.forEach((item,index)=>{totalAmount+=item.subtotal;const row=document.createElement('tr');row.innerHTML=`<td class="px-4 py-4 font-semibold text-med-ink">${item.name}</td><td class="px-4 py-4 text-med-muted">${item.price}</td><td class="px-4 py-4 text-med-muted">${item.quantity}</td><td class="px-4 py-4 text-med-ink">${item.subtotal}</td><td class="px-4 py-4 text-right"><button type="button" class="text-sm font-semibold text-med-danger" onclick="removeItem(${index})">Remove</button></td>`;tableBody.appendChild(row)});totalDisplay.innerText=totalAmount;document.getElementById('total_amount').value=totalAmount}function removeItem(index){transactionItems.splice(index,1);renderTable();document.getElementById('itemsInput').value=JSON.stringify(transactionItems)}document.getElementById('transactionForm').addEventListener('submit',function(){document.getElementById('itemsInput').value=JSON.stringify(transactionItems)});</script>
@endsection
