@extends('layouts.modern')

@section('title', 'Pharmacy Transaction Report')

@section('content')
    <x-ui.page title="Transaction Report" subtitle="Pharmacy sales and dispensing summary.">
        <x-slot:actions><a href="{{ route('pharmacy.transactions.index') }}" class="mf-focus inline-flex items-center justify-center gap-2 rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink shadow-sm transition hover:bg-med-canvas"><i class="bi bi-arrow-left"></i>Transactions</a></x-slot:actions>
        <form method="GET" action="{{ route('pharmacy.transactions.report') }}"><x-ui.card title="Report Filters"><div class="grid gap-4 md:grid-cols-3 md:items-end"><x-ui.input label="From" type="date" name="from" value="{{ $from }}" /><x-ui.input label="To" type="date" name="to" value="{{ $to }}" /><x-ui.button type="submit"><i class="bi bi-search"></i>Filter</x-ui.button></div></x-ui.card></form>
        <div class="grid gap-4 md:grid-cols-3"><x-ui.card><p class="text-sm font-medium text-med-muted">Transactions</p><p class="mt-2 text-2xl font-bold text-med-ink">{{ number_format($transactions->count()) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Items Dispensed</p><p class="mt-2 text-2xl font-bold text-med-ink">{{ number_format($transactions->flatMap->stockTransactionItems->sum('quantity')) }}</p></x-ui.card><x-ui.card><p class="text-sm font-medium text-med-muted">Total Amount</p><p class="mt-2 text-2xl font-bold text-med-ink">&#8358;{{ number_format($transactions->sum('total_amount'), 2) }}</p></x-ui.card></div>
        <x-ui.card title="Transactions"><x-ui.table class="shadow-none"><thead class="bg-med-canvas text-left text-xs font-semibold uppercase text-med-muted"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Reference</th><th class="px-4 py-3">Medicines</th><th class="px-4 py-3">Created By</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-med-line bg-white">@forelse($transactions as $transaction)<tr><td class="px-4 py-4 text-med-muted">{{ $transaction->created_at?->format('M d, Y h:i A') }}</td><td class="px-4 py-4 font-semibold text-med-ink">{{ $transaction->reference ?? $transaction->id }}</td><td class="px-4 py-4 text-med-muted">@foreach($transaction->stockTransactionItems as $item)<div>{{ $item->medicineBatch?->medicine?->name ?? 'N/A' }} <span>x {{ $item->quantity }}</span></div>@endforeach</td><td class="px-4 py-4 text-med-muted">{{ $transaction->createdBy?->name ?? 'System' }}</td><td class="px-4 py-4 text-right font-semibold text-med-ink">&#8358;{{ number_format($transaction->total_amount, 2) }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-8"><x-ui.empty-state title="No Transaction Found" message="No transaction was found for this period." /></td></tr>@endforelse</tbody></x-ui.table></x-ui.card>
    </x-ui.page>
@endsection
