@extends('layouts.modern')

@section('title', 'ANC Patient Medications')

@section('content')
@php
    $visit = $patient->currentVisit();
    $prescriptions = $prescriptions ?? ($visit ? $visit->prescriptions()->with(['prescriptionItems.medicine', 'prescribedBy'])->latest()->get() : collect());
    $investigations = $investigations ?? collect();
    $latestAncVisit = $latestAncVisit ?? $patient->latestAntenatalCare();
@endphp
<x-ui.page title="ANC Patient Medications" subtitle="{{ $patient->name() }} - Hospital No: {{ $patient->hospital_number }}">
    <div class="space-y-6">
        <div class="grid gap-4 md:grid-cols-4"><x-ui.card><p class="text-sm text-med-muted">Total Prescriptions</p><p class="mt-2 text-2xl font-semibold text-med-primary">{{ $prescriptions->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Active Prescriptions</p><p class="mt-2 text-2xl font-semibold text-med-success">{{ $prescriptions->where('status', 'active')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Investigations</p><p class="mt-2 text-2xl font-semibold text-med-warning">{{ $investigations->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Stopped Drugs</p><p class="mt-2 text-2xl font-semibold text-med-danger">{{ $prescriptions->where('status', 'stopped')->count() }}</p></x-ui.card></div>
        <div class="grid gap-6 xl:grid-cols-12"><div class="xl:col-span-8"><x-ui.card title="Drug Prescriptions" subtitle="{{ $prescriptions->count() }} records"><div class="divide-y divide-med-line">@forelse($prescriptions as $prescription)<article class="py-4 first:pt-0 last:pb-0"><div class="grid gap-4 lg:grid-cols-[1fr_140px_140px_130px_160px]"><div><p class="text-xs uppercase text-med-muted">Prescription</p><p class="font-semibold text-med-ink">{{ $prescription->drug_name ?? $prescription->prescriptionItems->pluck('medicine.name')->filter()->join(', ') ?: 'Prescription #' . $prescription->id }}</p><p class="text-sm text-med-muted">{{ $prescription->dosage ?? $prescription->prescriptionItems->pluck('dosage')->filter()->join(', ') ?: 'N/A' }}</p></div><div><p class="text-xs uppercase text-med-muted">Frequency</p><p class="font-semibold text-med-ink">{{ $prescription->frequency ?? 'N/A' }}</p></div><div><p class="text-xs uppercase text-med-muted">Duration</p><p class="font-semibold text-med-ink">{{ $prescription->duration ?? 'N/A' }}</p></div><div><p class="text-xs uppercase text-med-muted">Status</p><x-ui.badge variant="{{ $prescription->status === 'active' ? 'success' : ($prescription->status === 'completed' ? 'info' : 'danger') }}">{{ str($prescription->status ?? 'pending')->headline() }}</x-ui.badge></div><div><p class="text-xs uppercase text-med-muted">Prescribed By</p><p class="font-semibold text-med-ink">{{ $prescription->prescribedBy->name ?? 'N/A' }}</p></div></div>@if($prescription->instruction)<p class="mt-3 rounded-md border border-med-line bg-med-canvas px-3 py-2 text-sm text-med-ink">{{ $prescription->instruction }}</p>@endif</article>@empty<x-ui.empty-state title="No drug prescriptions found" message="No medication has been prescribed for this ANC patient yet." />@endforelse</div></x-ui.card></div>
        <aside class="space-y-6 xl:col-span-4"><x-ui.card title="Investigations" subtitle="{{ $investigations->count() }} records"><div class="divide-y divide-med-line">@forelse($investigations as $investigation)<article class="py-3 first:pt-0 last:pb-0"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold text-med-ink">{{ $investigation->investigation_name ?? 'Investigation #' . $investigation->id }}</p><p class="text-sm text-med-muted">{{ $investigation->created_at?->format('M d, Y') ?? 'N/A' }}</p></div><x-ui.badge variant="{{ $investigation->status === 'completed' ? 'success' : ($investigation->status === 'pending' ? 'warning' : 'info') }}">{{ str($investigation->status ?? 'requested')->headline() }}</x-ui.badge></div>@if($investigation->result)<p class="mt-2 rounded-md border border-med-line bg-med-canvas px-3 py-2 text-sm text-med-ink">{{ Str::limit($investigation->result, 150) }}</p>@endif</article>@empty<x-ui.empty-state title="No investigations" message="No ANC investigations are attached to this page." />@endforelse</div></x-ui.card><x-ui.card title="Patient Information"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Patient Name</dt><dd class="font-semibold text-med-ink">{{ $patient->name() }}</dd></div><div><dt class="text-med-muted">Hospital Number</dt><dd class="font-semibold text-med-ink">{{ $patient->hospital_number }}</dd></div><div><dt class="text-med-muted">Phone Number</dt><dd class="font-semibold text-med-ink">{{ $patient->demographic?->phone_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Last ANC Visit</dt><dd class="font-semibold text-med-ink">{{ $latestAncVisit?->created_at?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div></dl></x-ui.card></aside></div>
    </div>
</x-ui.page>
@endsection
