<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>My Activities Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ddd; padding: 6px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { width: 100%; border-bottom: 2px solid #198754; padding-bottom: 10px; margin-bottom: 12px; }
        .header td { border: 0; padding: 0; }
        .logo { width: 78px; height: 78px; object-fit: contain; }
        .hospital-name { font-size: 18px; font-weight: bold; color: #198754; }
        .report-meta { font-size: 10px; color: #555; text-align: right; }
        .text-end { text-align: right; }
        .summary td { width: 50%; }
        .muted { color: #666; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 90px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>My Activities Report</h1>
                <div class="muted">{{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</div>
            </td>
            <td class="report-meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Total Activities</strong><br>{{ number_format($summary['total']) }}</td>
            <td><strong>Activity Types</strong><br>{{ number_format($summary['activity_types']) }}</td>
        </tr>
    </table>

    <h2>Activity Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Activity</th>
                <th class="text-end">Count</th>
            </tr>
        </thead>
        <tbody>
            @forelse($typeBreakdown as $row)
                <tr>
                    <td>{{ $row->label }}</td>
                    <td class="text-end">{{ number_format($row->count) }}</td>
                </tr>
            @empty
                <tr><td colspan="2">No activity found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Activity Details</h2>
    <table>
        <thead>
            <tr>
                <th>Activity</th>
                <th>Details</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($activities as $activity)
                <tr>
                    <td>{{ $activity->activity_label }}</td>
                    <td>{{ $activity->subject ?? 'Record #' . $activity->id }}</td>
                    <td>{{ \Carbon\Carbon::parse($activity->occurred_at)->format('Y-m-d H:i') }}</td>
                </tr>
            @empty
                <tr><td colspan="3">No activities found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
