<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ddd; padding: 6px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { width: 100%; border-bottom: 2px solid #198754; padding-bottom: 10px; margin-bottom: 12px; }
        .header td { border: 0; padding: 0; }
        .logo { width: 78px; height: 78px; object-fit: contain; }
        .hospital-name { font-size: 18px; font-weight: bold; color: #198754; }
        .report-meta { font-size: 10px; color: #555; text-align: right; }
        .text-end { text-align: right; }
        .summary td { width: 25%; }
        .muted { color: #666; }
        .positive { color: #0f7a39; }
        .negative { color: #b42318; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 90px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Payment Report</h1>
                <div class="muted">{{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</div>
            </td>
            <td class="report-meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Payments</strong><br>{{ number_format($summary['payment_count']) }}</td>
            <td><strong>Completed</strong><br>{{ number_format($summary['completed_amount'], 2) }}</td>
            <td><strong>Pending</strong><br>{{ number_format($summary['pending_amount'], 2) }}</td>
            <td><strong>Reversed</strong><br>{{ number_format($summary['reversed_amount'], 2) }}</td>
        </tr>
        <tr>
            <td><strong>Other Revenue</strong><br>{{ number_format($summary['total_revenue'], 2) }}</td>
            <td><strong>Expenses</strong><br>{{ number_format($summary['total_expense'], 2) }}</td>
            <td colspan="2"><strong>Net Position</strong><br><span class="{{ $summary['net_position'] >= 0 ? 'positive' : 'negative' }}">{{ number_format($summary['net_position'], 2) }}</span></td>
        </tr>
    </table>

    <h2>Payment Details</h2>
    <table>
        <thead>
            <tr>
                <th>Payment ID</th>
                <th>Patient</th>
                <th>Bill #</th>
                <th class="text-end">Amount</th>
                <th>Method</th>
                <th>Status</th>
                <th>Recorded By</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $payment)
                @php
                    $patientName = $payment->bill?->walkinPatient?->name
                        ?? $payment->bill?->patientVisit?->patient?->name()
                        ?? 'N/A';
                @endphp
                <tr>
                    <td>{{ $payment->payment_id }}</td>
                    <td>{{ $patientName }}</td>
                    <td>{{ $payment->bill?->bill_number ?? 'N/A' }}</td>
                    <td class="text-end">{{ number_format($payment->amount, 2) }}</td>
                    <td>{{ $payment->paymentMethod->name ?? 'N/A' }}</td>
                    <td>{{ ucfirst($payment->status) }}</td>
                    <td>{{ $payment->recordedBy->name ?? 'N/A' }}</td>
                    <td>{{ $payment->payment_date?->format('Y-m-d H:i') }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No payments found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Other Revenue</h2>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Title</th>
                <th>Department</th>
                <th class="text-end">Amount</th>
                <th>Date</th>
                <th>Recorded By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($revenues as $revenue)
                <tr>
                    <td>{{ $revenue->category->name ?? 'N/A' }}</td>
                    <td>{{ $revenue->title }}</td>
                    <td>{{ $revenue->department->name ?? 'General' }}</td>
                    <td class="text-end">{{ number_format($revenue->amount, 2) }}</td>
                    <td>{{ $revenue->revenue_date?->format('Y-m-d') }}</td>
                    <td>{{ $revenue->createdBy->name ?? 'System' }}</td>
                </tr>
            @empty
                <tr><td colspan="6">No revenue found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Expenses</h2>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Title</th>
                <th>Department</th>
                <th class="text-end">Amount</th>
                <th>Date</th>
                <th>Recorded By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($expenses as $expense)
                <tr>
                    <td>{{ $expense->category->name ?? 'N/A' }}</td>
                    <td>{{ $expense->title }}</td>
                    <td>{{ $expense->department->name ?? 'N/A' }}</td>
                    <td class="text-end">{{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->expense_date?->format('Y-m-d') }}</td>
                    <td>{{ $expense->createdBy->name ?? 'System' }}</td>
                </tr>
            @empty
                <tr><td colspan="6">No expenses found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
