<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Revenue Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { border-bottom: 2px solid #198754; padding-bottom: 10px; margin-bottom: 12px; }
        .header td { border: 0; padding: 0; }
        .logo { width: 78px; height: 78px; object-fit: contain; }
        .hospital-name { font-size: 18px; font-weight: bold; color: #198754; }
        .report-meta { font-size: 10px; color: #555; text-align: right; }
        .text-end { text-align: right; }
        .summary td { width: 33.33%; }
        .muted { color: #666; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 90px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Revenue Report</h1>
                <div class="muted">
                    {{ $filters['date_from'] ?: 'Beginning' }} to {{ $filters['date_to'] ?: now()->format('Y-m-d') }}
                    @if($filters['search'])
                        | Search: {{ $filters['search'] }}
                    @endif
                </div>
            </td>
            <td class="report-meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Records</strong><br>{{ number_format($summary['count']) }}</td>
            <td><strong>Total Revenue</strong><br>{{ number_format($summary['total'], 2) }}</td>
            <td><strong>Average Revenue</strong><br>{{ number_format($summary['average'], 2) }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Title</th>
                <th>Reference</th>
                <th>Department</th>
                <th class="text-end">Amount</th>
                <th>Date</th>
                <th>Recorded By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $revenue)
                <tr>
                    <td>{{ $revenue->category->name ?? 'N/A' }}</td>
                    <td>{{ $revenue->title }}</td>
                    <td>{{ $revenue->reference_number ?? '-' }}</td>
                    <td>{{ $revenue->department->name ?? 'General' }}</td>
                    <td class="text-end">{{ number_format($revenue->amount, 2) }}</td>
                    <td>{{ $revenue->revenue_date?->format('Y-m-d') }}</td>
                    <td>{{ $revenue->createdBy->name ?? 'System' }}</td>
                </tr>
            @empty
                <tr><td colspan="7">No revenue found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
