@php
    $record = $newborn ?? null;
    $delivery = $delivery ?? $record?->delivery;
    $patient = $record?->patient ?? $delivery?->patient;
    $fieldClass = 'mf-focus block w-full rounded-md border border-med-line px-3 py-2.5 text-sm text-med-ink shadow-sm placeholder:text-med-muted/70';
    $labelClass = 'mb-1 block text-sm font-medium text-med-ink';
    $value = fn ($name, $default = '') => old($name, data_get($record, $name, $default));
    $dateValue = fn ($name, $default = null) => old($name, data_get($record, $name)?->format('Y-m-d\TH:i') ?? $default);
@endphp
@if ($errors->any())<div class="rounded-md border border-med-danger/25 bg-red-50 px-4 py-3 text-sm text-med-danger"><p class="font-semibold">Please fix the highlighted errors.</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 xl:grid-cols-12"><div class="space-y-6 xl:col-span-8">
<x-ui.card title="Newborn Information"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Sex</span><select name="sex" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['male'=>'Male','female'=>'Female'] as $key=>$label)<option value="{{ $key }}" @selected($value('sex','female')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Birth Order</span><input type="number" min="1" max="10" name="birth_order" value="{{ $value('birth_order', 1) }}" class="{{ $fieldClass }}"></label>@if($record)<label><span class="{{ $labelClass }}">Registration Number</span><input type="text" name="newborn_registration_number" value="{{ $value('newborn_registration_number') }}" class="{{ $fieldClass }}"></label>@endif<label><span class="{{ $labelClass }}">Birth Date & Time</span><input type="datetime-local" name="birth_date_time" value="{{ $dateValue('birth_date_time', $delivery?->delivery_date_time?->format('Y-m-d\TH:i') ?? now()->format('Y-m-d\TH:i')) }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Presentation</span><select name="presentation" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['cephalic'=>'Cephalic','breech'=>'Breech','transverse'=>'Transverse','face'=>'Face'] as $key=>$label)<option value="{{ $key }}" @selected($value('presentation')===$key)>{{ $label }}</option>@endforeach</select></label><label><span class="{{ $labelClass }}">Status</span><select name="status" class="{{ $fieldClass }}"><option value="">Select</option>@foreach(['alive'=>'Alive','stillborn'=>'Stillborn','early_neonatal_death'=>'Early Neonatal Death'] as $key=>$label)<option value="{{ $key }}" @selected($value('status','alive')===$key)>{{ $label }}</option>@endforeach</select></label><label class="md:col-span-3"><span class="{{ $labelClass }}">Delivery Notes</span><textarea name="delivery_notes" rows="3" class="{{ $fieldClass }}">{{ $value('delivery_notes') }}</textarea></label></div></x-ui.card>
<x-ui.card title="Measurements And APGAR"><div class="grid gap-4 md:grid-cols-3"><label><span class="{{ $labelClass }}">Birth Weight</span><input type="text" name="birth_weight" value="{{ $value('birth_weight') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Birth Length</span><input type="text" name="birth_length" value="{{ $value('birth_length') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">Head Circumference</span><input type="text" name="head_circumference" value="{{ $value('head_circumference') }}" class="{{ $fieldClass }}"></label>@foreach(['apgar_score_1_minute'=>'APGAR 1 Minute','apgar_score_5_minutes'=>'APGAR 5 Minutes','apgar_score_10_minutes'=>'APGAR 10 Minutes','apgar_appearance_1min'=>'Appearance 1 Min','apgar_pulse_1min'=>'Pulse 1 Min','apgar_grimace_1min'=>'Grimace 1 Min','apgar_activity_1min'=>'Activity 1 Min','apgar_respiration_1min'=>'Respiration 1 Min'] as $name=>$label)<label><span class="{{ $labelClass }}">{{ $label }}</span><input type="number" min="0" max="10" name="{{ $name }}" value="{{ $value($name) }}" class="{{ $fieldClass }}"></label>@endforeach</div></x-ui.card>
<x-ui.card title="Condition And Care"><div class="grid gap-4 md:grid-cols-2"><label><span class="{{ $labelClass }}">General Condition</span><input type="text" name="general_condition" value="{{ $value('general_condition') }}" class="{{ $fieldClass }}"></label><label><span class="{{ $labelClass }}">First Breastfeed Time</span><input type="datetime-local" name="first_breastfeed_time" value="{{ $dateValue('first_breastfeed_time') }}" class="{{ $fieldClass }}"></label>@foreach(['physical_examination'=>'Physical Examination','birth_defects_noted'=>'Birth Defects Noted','meconium_aspiration'=>'Meconium Aspiration','feeding_problems'=>'Feeding Problems','immunizations_details'=>'Immunizations Details','screening_test_results'=>'Screening Test Results','special_care_needed'=>'Special Care Needed','referred_to'=>'Referred To','neonatal_observations'=>'Neonatal Observations'] as $name=>$label)<label class="md:col-span-2"><span class="{{ $labelClass }}">{{ $label }}</span><textarea name="{{ $name }}" rows="3" class="{{ $fieldClass }}">{{ $value($name) }}</textarea></label>@endforeach<div class="md:col-span-2 grid gap-3 sm:grid-cols-2">@foreach(['breastfeeding_initiated'=>'Breastfeeding Initiated','vitamin_k_given'=>'Vitamin K Given','eye_prophylaxis_given'=>'Eye Prophylaxis Given','immunizations_given'=>'Immunizations Given','screening_test_done'=>'Screening Test Done'] as $name=>$label)<label class="flex items-center gap-2 text-sm font-medium text-med-ink"><input type="checkbox" name="{{ $name }}" value="1" class="rounded border-med-line text-med-primary focus:ring-med-primary" @checked((bool) $value($name))> {{ $label }}</label>@endforeach</div></div></x-ui.card>
</div><aside class="space-y-6 xl:col-span-4"><x-ui.card title="Delivery Context"><dl class="space-y-3 text-sm"><div><dt class="text-med-muted">Mother</dt><dd class="font-semibold text-med-ink">{{ $patient?->name() ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Hospital Number</dt><dd class="font-semibold text-med-ink">{{ $patient?->hospital_number ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Delivery Type</dt><dd class="font-semibold text-med-ink">{{ str($delivery?->delivery_type ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Delivery Date</dt><dd class="font-semibold text-med-ink">{{ $delivery?->delivery_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div></dl></x-ui.card><x-ui.card title="Save Newborn"><div class="flex flex-col gap-2"><x-ui.button type="submit">{{ $submitLabel ?? 'Save Newborn' }}</x-ui.button><a href="{{ $cancelRoute ?? route('midwife.newborn.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Cancel</a></div></x-ui.card></aside></div>
