<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Pharmacy Stock Taking Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #222; }
        h1 { font-size: 19px; margin: 0 0 4px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 5px; vertical-align: top; }
        th { background: #f3f5f7; text-align: left; }
        .header { border-bottom: 2px solid #198754; margin-bottom: 10px; }
        .header td { border: 0; padding: 0 0 8px; }
        .logo { width: 70px; height: 70px; object-fit: contain; }
        .hospital-name { font-size: 17px; font-weight: bold; color: #198754; }
        .meta { text-align: right; color: #555; }
        .summary td { width: 25%; }
        .text-end { text-align: right; }
        .muted { color: #666; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td style="width: 84px;">
                @if(!empty($hospital['logo']) && file_exists($hospital['logo']))
                    <img src="{{ $hospital['logo'] }}" class="logo" alt="Hospital Logo">
                @endif
            </td>
            <td>
                <div class="hospital-name">{{ $hospital['name'] }}</div>
                <div>{{ $hospital['address'] }}</div>
                <h1>Pharmacy Stock Taking Report</h1>
                <div class="muted">
                    @if($from || $to)
                        Period: {{ $from ?: 'Beginning' }} to {{ $to ?: now()->toDateString() }}
                    @else
                        Current stock position
                    @endif
                </div>
                @if($search || $expiryStatus)
                    <div class="muted">Filters: {{ $search ?: 'All medicines' }} {{ $expiryStatus ? '| ' . ucfirst($expiryStatus) : '' }}</div>
                @endif
            </td>
            <td class="meta" style="width: 210px;">
                <strong>Generated By:</strong><br>
                {{ $generatedBy->name ?? 'System' }}<br>
                {{ $generatedBy->email ?? '' }}<br><br>
                <strong>Generated At:</strong><br>
                {{ now()->format('M d, Y H:i') }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td><strong>Medicines / Batches</strong><br>{{ number_format($summary['medicines']) }} / {{ number_format($summary['batches']) }}</td>
            <td><strong>Quantity Remaining</strong><br>{{ number_format($summary['quantity']) }}</td>
            <td><strong>Purchase Value</strong><br>{{ number_format($summary['purchase_value'], 2) }}</td>
            <td><strong>Retail Value</strong><br>{{ number_format($summary['retail_value'], 2) }}</td>
        </tr>
    </table>

    <br>

    <table>
        <thead>
            <tr>
                <th>Medicine</th>
                <th>Type</th>
                <th class="text-end">Batches</th>
                <th class="text-end">Received</th>
                <th class="text-end">Remaining</th>
                <th class="text-end">Avg Purchase</th>
                <th class="text-end">Next Selling</th>
                <th class="text-end">Retail Value</th>
                <th>Nearest Expiry</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stocks as $medicine)
                @php
                    $medicineBatches = $medicine->batches;
                    $quantityReceived = (int) $medicineBatches->sum('quantity_received');
                    $quantityRemaining = (int) $medicineBatches->sum('quantity_remaining');
                    $purchaseValue = (float) $medicineBatches->sum(fn($batch) => $batch->quantity_remaining * $batch->purchase_price);
                    $retailValue = (float) $medicineBatches->sum(fn($batch) => $batch->quantity_remaining * $batch->selling_price);
                    $averagePurchase = $quantityRemaining > 0 ? $purchaseValue / $quantityRemaining : 0;
                    $nextBatch = $medicineBatches->where('quantity_remaining', '>', 0)->where('expiry_date', '>=', today()->toDateString())->sortBy('expiry_date')->first();
                    $nearestExpiry = $medicineBatches->where('quantity_remaining', '>', 0)->sortBy('expiry_date')->first()?->expiry_date;
                    $expired = $nearestExpiry ? \Carbon\Carbon::parse($nearestExpiry)->isPast() : false;
                    $expiring = $nearestExpiry && ! $expired && \Carbon\Carbon::parse($nearestExpiry)->lte(today()->addDays(60));
                @endphp
                <tr>
                    <td>{{ $medicine->name }}</td>
                    <td>{{ $medicine->medicineType?->name ?? 'N/A' }}</td>
                    <td class="text-end">{{ number_format($medicineBatches->count()) }}</td>
                    <td class="text-end">{{ number_format($quantityReceived) }}</td>
                    <td class="text-end">{{ number_format($quantityRemaining) }}</td>
                    <td class="text-end">{{ number_format($averagePurchase, 2) }}</td>
                    <td class="text-end">{{ number_format($nextBatch?->selling_price ?? 0, 2) }}</td>
                    <td class="text-end">{{ number_format($retailValue, 2) }}</td>
                    <td>{{ $nearestExpiry ?? 'N/A' }}</td>
                    <td>{{ $quantityRemaining <= 0 ? 'Out' : ($expired ? 'Expired' : ($expiring ? 'Expiring' : 'Valid')) }}</td>
                </tr>
            @empty
                <tr><td colspan="10">No medicine stock found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
