@extends('layouts.modern')

@section('title', 'Postnatal Examination Records')

@section('content')
@php($examinations = $delivery->postnatalExaminations->sortByDesc('examination_date_time'))
<x-ui.page title="Postnatal Examination Records" subtitle="Mother: {{ $delivery->patient->name() }} - {{ str($delivery->delivery_type ?? 'delivery')->headline() }}">
    <x-slot name="actions"><a href="{{ route('midwife.postnatal-examination.create', $delivery) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">New Examination</a><a href="{{ route('midwife.delivery.show', $delivery) }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6"><x-ui.card title="Delivery Summary"><dl class="grid gap-4 text-sm md:grid-cols-4"><div><dt class="text-med-muted">Delivery Date</dt><dd class="font-semibold text-med-ink">{{ $delivery->delivery_date_time?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Delivery Type</dt><dd class="font-semibold text-med-ink">{{ str($delivery->delivery_type ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Delivery Status</dt><dd><x-ui.badge variant="{{ $delivery->delivery_status === 'successful' ? 'success' : ($delivery->delivery_status === 'complicated' ? 'warning' : 'danger') }}">{{ str($delivery->delivery_status)->headline() }}</x-ui.badge></dd></div><div><dt class="text-med-muted">Number of Babies</dt><dd class="font-semibold text-med-ink">{{ $delivery->number_of_babies ?? 'N/A' }}</dd></div></dl></x-ui.card>
    <div class="grid gap-4 md:grid-cols-3"><x-ui.card><p class="text-sm text-med-muted">Total Examinations</p><p class="mt-2 text-2xl font-semibold text-med-ink">{{ $examinations->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Normal Recovery</p><p class="mt-2 text-2xl font-semibold text-med-success">{{ $examinations->where('recovery_status', 'normal')->count() }}</p></x-ui.card><x-ui.card><p class="text-sm text-med-muted">Needs Attention</p><p class="mt-2 text-2xl font-semibold text-med-warning">{{ $examinations->where('recovery_status', '!=', 'normal')->count() }}</p></x-ui.card></div>
    <x-ui.card title="Recovery Timeline" subtitle="{{ $examinations->count() }} records"><div class="divide-y divide-med-line">@forelse($examinations as $examination)<article class="py-4 first:pt-0 last:pb-0"><div class="grid gap-4 lg:grid-cols-[170px_160px_1fr_140px_auto]"><div><p class="text-xs uppercase text-med-muted">Examination Date</p><p class="font-semibold text-med-ink">{{ $examination->examination_date_time?->format('M d, Y') ?? 'N/A' }}</p><p class="text-sm text-med-muted">{{ $examination->examination_date_time?->format('h:i A') }}</p></div><div><p class="text-xs uppercase text-med-muted">Recovery</p><x-ui.badge variant="{{ $examination->recovery_status === 'normal' ? 'success' : ($examination->recovery_status === 'complicated' ? 'warning' : 'danger') }}">{{ str($examination->recovery_status)->headline() }}</x-ui.badge></div><div class="text-sm text-med-muted"><span class="font-medium text-med-ink">Vitals:</span> BP {{ $examination->blood_pressure ?? 'N/A' }}, Pulse {{ $examination->pulse_rate ?? 'N/A' }}, Temp {{ $examination->temperature ?? 'N/A' }}<br>@if($examination->clinical_summary)<span class="font-medium text-med-ink">Summary:</span> {{ Str::limit($examination->clinical_summary, 220) }}@endif @if($examination->next_follow_up_date)<p class="mt-2 font-medium text-med-warning">Next follow-up: {{ $examination->next_follow_up_date?->format('M d, Y h:i A') }}</p>@endif</div><div><p class="text-xs uppercase text-med-muted">Recorded By</p><p class="font-semibold text-med-ink">{{ $examination->recordedBy->name ?? 'N/A' }}</p></div><div class="flex justify-end gap-2"><a href="{{ route('midwife.postnatal-examination.show', $examination) }}" class="text-sm font-semibold text-med-primary hover:text-med-primaryDark">View</a><a href="{{ route('midwife.postnatal-examination.edit', $examination) }}" class="text-sm font-semibold text-med-info hover:text-blue-700">Edit</a></div></div></article>@empty<x-ui.empty-state title="No postnatal examinations" message="No recovery checks have been recorded for this delivery." />@endforelse</div></x-ui.card></div>
</x-ui.page>
@endsection
