@extends('layouts.modern')

@section('title', 'Postnatal Examination Details')

@section('content')
@php
    $delivery = $postnatalExamination->delivery;
    $patient = $postnatalExamination->patient ?? $delivery?->patient;
@endphp
<x-ui.page title="Postnatal Examination Details" subtitle="{{ $patient?->name() ?? 'Patient' }} - {{ $postnatalExamination->examination_date_time?->format('M d, Y h:i A') ?? 'N/A' }}">
    <x-slot name="actions"><a href="{{ route('midwife.postnatal-examination.edit', $postnatalExamination) }}" class="inline-flex items-center justify-center rounded-md border border-med-primary bg-med-primary px-3 py-2 text-sm font-semibold text-white transition hover:bg-med-primaryDark">Edit</a><a href="{{ $delivery ? route('midwife.postnatal-examination.record', $delivery) : route('midwife.postnatal-examination.index') }}" class="inline-flex items-center justify-center rounded-md border border-med-line bg-white px-3 py-2 text-sm font-semibold text-med-ink transition hover:bg-med-canvas">Back</a></x-slot>
    <div class="space-y-6"><x-ui.card title="Summary"><dl class="grid gap-4 text-sm md:grid-cols-4"><div><dt class="text-med-muted">Recovery Status</dt><dd><x-ui.badge variant="{{ $postnatalExamination->recovery_status === 'normal' ? 'success' : ($postnatalExamination->recovery_status === 'complicated' ? 'warning' : 'danger') }}">{{ str($postnatalExamination->recovery_status)->headline() }}</x-ui.badge></dd></div><div><dt class="text-med-muted">Examination Time</dt><dd class="font-semibold text-med-ink">{{ str($postnatalExamination->examination_time ?? 'N/A')->headline() }}</dd></div><div><dt class="text-med-muted">Hours Post Delivery</dt><dd class="font-semibold text-med-ink">{{ $postnatalExamination->hours_post_delivery ?? 'N/A' }}</dd></div><div><dt class="text-med-muted">Recorded By</dt><dd class="font-semibold text-med-ink">{{ $postnatalExamination->recordedBy->name ?? 'N/A' }}</dd></div></dl></x-ui.card>
    <div class="grid gap-4 md:grid-cols-4">@foreach(['blood_pressure'=>'Blood Pressure','pulse_rate'=>'Pulse Rate','temperature'=>'Temperature','respiration_rate'=>'Respiration Rate'] as $field=>$label)<x-ui.card><p class="text-xs uppercase text-med-muted">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-med-ink">{{ $postnatalExamination->{$field} ?? 'N/A' }}</p></x-ui.card>@endforeach</div>
    <x-ui.card title="Assessment Details"><dl class="grid gap-4 text-sm md:grid-cols-2">@foreach(['general_appearance'=>'General Appearance','consciousness_level'=>'Consciousness Level','skin_colour'=>'Skin Colour','uterine_size'=>'Uterine Size','uterine_consistency'=>'Uterine Consistency','uterine_tenderness'=>'Uterine Tenderness','fundal_height'=>'Fundal Height','lochia_type'=>'Lochia Type','lochia_amount'=>'Lochia Amount','lochia_odour'=>'Lochia Odour','perineal_assessment'=>'Perineal Assessment','perineal_wound_status'=>'Perineal Wound Status','perineal_pain'=>'Perineal Pain','vaginal_examination'=>'Vaginal Examination','breast_examination'=>'Breast Examination','nipple_condition'=>'Nipple Condition','breast_engorgement'=>'Breast Engorgement','breast_milk_expression'=>'Breast Milk Expression','breastfeeding_problems'=>'Breastfeeding Problems','abdominal_examination'=>'Abdominal Examination','wound_assessment'=>'Wound Assessment','drain_status'=>'Drain Status','lower_limbs_examination'=>'Lower Limbs Examination','oedema_assessment'=>'Oedema Assessment','calf_tenderness'=>'Calf Tenderness','signs_of_dvt'=>'Signs Of DVT','maternal_mood'=>'Maternal Mood','emotional_state'=>'Emotional State','bonding_with_baby'=>'Bonding With Baby'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $postnatalExamination->{$field} ?: 'N/A' }}</dd></div>@endforeach</dl></x-ui.card>
    <x-ui.card title="Management"><dl class="grid gap-4 text-sm md:grid-cols-2">@foreach(['clinical_summary'=>'Clinical Summary','management_plan'=>'Management Plan','medications_prescribed'=>'Medications Prescribed','follow_up_plan'=>'Follow-up Plan','contraception_method_chosen'=>'Contraception Method Chosen'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-med-ink">{{ $postnatalExamination->{$field} ?: 'N/A' }}</dd></div>@endforeach<div><dt class="font-medium text-med-muted">Next Follow-up Date</dt><dd class="font-semibold text-med-ink">{{ $postnatalExamination->next_follow_up_date?->format('M d, Y h:i A') ?? 'N/A' }}</dd></div>@foreach(['clot_presence'=>'Clot Presence','breastfeeding_successful'=>'Breastfeeding Successful','signs_of_depression'=>'Signs Of Depression','contraception_discussed'=>'Contraception Discussed'] as $field=>$label)<div><dt class="font-medium text-med-muted">{{ $label }}</dt><dd><x-ui.badge variant="{{ $postnatalExamination->{$field} ? 'success' : 'danger' }}">{{ $postnatalExamination->{$field} ? 'Yes' : 'No' }}</x-ui.badge></dd></div>@endforeach</dl></x-ui.card></div>
</x-ui.page>
@endsection
